### ISSUE TITLE
Use without PIAF

### ISSUE THREAD

**Issue by palitu** [GridProtectionAlliance/osisoftpi-grafana#1]
Is it possible to use this to extract data directly from the Pi Servers, without going through a PI AF server?

We have decided not to go down the PIAF route, as there is just too much work to get everything into the right framework.

thanks.

Leigh

**Comment by EEParker** [comment]
Currently this plugin does not have any way to access PI directly. This plugin uses PI WebAPI as the data source, which requires an AF Server.  

There is some framework in progress (not yet complete) in the retrieve PI tags data by tag names, however this will still require PI WebAPI and PI-AF to be installed and running.

**Comment by palitu** [comment]
Thanks,  We have 15 sites, with 100's of thousands of tags, and no nice way of visualising them.

cheers,

**Comment by EEParker** [comment]
Without installing PI AF and PI WebAPI, you have a couple options to visualize data in Grafana. 

One would be to create a web service using AFSDK that connects directly to PI (without AF) and mimics the PI WebAPI interface. Optionally it could have it's own data structure, but a new custom Grafana Datasource would be required.

I'm not sure that this help your case much, but in cases where we have data that does not have a native web interface we have used InfluxDB as an intermediate data source. By sending a copy of the data to InfluxDB it is them possible to use Grafana as the front end for visualization. There are some downsides to this approach, such as having to maintain more software and data sources, as well as configuring a connector to get data into Influx. However, Influx is very powerful and provides some nice analytic tools as well.
