### ISSUE TITLE
Add Allowed Databases to configuration

### ISSUE THREAD

**Issue by EEParker** [GridProtectionAlliance/osisoftpi-grafana#10]
This is part one of #6 as a new feature.

Add ability to lock datasource to only be able to use specific databases. This could be accomplished in one of two ways:

1. Make the current "Default Database" be "Database" and remove the ability to change databases from the metric configuration panel when selecting AF elements. This is similar to the way the InfluxDB datasource works, where each "database" requires a new instance of the datasource.

2. Add a checkable list box (or similar control) to the configuration for "Allowed" databases. These would be populated in the existing metric configuration panel. This would allow multiple databases to be used from a single datasource, but I think this is a fairly limited use case.

@rtmaster and other users, please let me know if you have a preference on which way this should be implemented with a comment, either 1 or 2.

**Comment by rtmaster** [comment]
Usually only a few people need access to multiple databases, plus 1 seems easier/faster to implement. I'm voting for 1 and maybe in a second stage 2 can come as an improvement if really needed.
These are just my 2 cents
Thanks

**Comment by rtmaster** [comment]
Hi @EEParker do you think it’s fair to say that Option #1 is the way to go at this point?

**Comment by rtmaster** [comment]
Hi @ritchiecarroll and @EEParker do you think it’s fair to say that Option #1 is the way to go at this point?

**Comment by coderReview** [comment]
@ritchiecarroll @clackner-gpa can we implement one of the above solution?

**Comment by coderReview** [comment]
cc @EEParker

**Comment by coderReview** [comment]
This has been implemented in v2.0.0-beta. @ritchiecarroll  @EEParker
