### ISSUE TITLE
Deploy version 3.1.0 to Grafana

### ISSUE THREAD

**Issue by coderReview** [GridProtectionAlliance/osisoftpi-grafana#106]
@clackner-gpa @elwills Have version 3.1.0 been deployed to Grafana? I can't find it yet in their web page.

**Comment by coderReview** [comment]
Hello @elwills any issues with the review. It's taking a long time.

**Comment by elwills** [comment]
Yes, they have let me know that there were some `console.log()` statements left in so it will need to be resubmitted once those are removed. I will try to get around to that today.

**Comment by coderReview** [comment]
I will make a new commit fixing this

**Comment by coderReview** [comment]
Next month I will release version 4.0. Have to do testing and additional verification.

**Comment by coderReview** [comment]
Fixed in https://github.com/GridProtectionAlliance/osisoftpi-grafana/pull/110

**Comment by coderReview** [comment]
Hello @elwills have the review been completed?

**Comment by elwills** [comment]
@coderReview it just passed review this morning and is now published! Thanks for your patience!!!
