### ISSUE TITLE
Deploy version 4.0.0 to Grafana

### ISSUE THREAD

**Issue by coderReview** [GridProtectionAlliance/osisoftpi-grafana#108]
Done in PR #107.

**Comment by coderReview** [comment]
Version 4.0.0 is almost done. Just need more testing.

**Comment by coderReview** [comment]
@elwills ready to be released.

**Comment by coderReview** [comment]
Hello @elwills and @clackner-gpa. Can you help releasing version 4.0.0?

Thank you.

**Comment by coderReview** [comment]
Merged.

**Comment by coderReview** [comment]
@elwills I saw you made a new release. Let me know if there is any issue. Thank you.

**Comment by elwills** [comment]
@coderReview Just waiting on a response from Grafana for next steps! I'll keep you updated.
