### ISSUE TITLE
Issue retrieving data from AF or Pi Points

### ISSUE THREAD

**Issue by jon-ton** [GridProtectionAlliance/osisoftpi-grafana#109]
Hello, 

First off thanks for the work on this plugin.

I'm trying to connect to our AF database via the piwebapi. I'm able to see the tag elements/attributes populate via AF, and the Pi Points tag names all populate properly, but when I select one, I only ever get **No Data** returned by the query. 

If I query via Postman/browser I'm able to get data, but not using the plugin. 

Grafana version = 9.3
PiWebAPI 2018 SP3

I was wondering if I have to upgrade to PiWebAPI 2021 or downgrade Grafana. Or if perhaps there's a good way to debug the values for the PI/AF Connection Details. 

Thanks,
Jon

**Comment by coderReview** [comment]
Click on Inspect->Query and look at the query being done to the PiWebAPI. This will help debugging.

**Comment by jon-ton** [comment]
Thanks coderReview. A little trial and error with the query inspector and it turned out to be the PiWebAPI version. If it helps anyone else, upgraded to 2021 SP3 and the plugin worked just fine. 

Looks like PiWebAPI changed syntax from 2018 to 2021.
