### ISSUE TITLE
Compatibility with the grafana v5.0 beta1

### ISSUE THREAD

**Issue by Aysha94** [GridProtectionAlliance/osisoftpi-grafana#11]
We are facing a compatibility issue between osisoft PI plugin and grafana V5.0 beta1. We would like to know when this issue will be resolved?

**Comment by ritchiecarroll** [comment]
Are you seeing errors upon use or is the new beta version just refusing to load plug-in?

**Comment by Aysha94** [comment]
when I want to add new data source of type (OSIsoft PI) I receive this error 

Plugin Error
XHR error: (404 Not Found) loading http://nabwgra1/public/app/plugins/datasource/gridprotectionalliance-osisoftpi-datasource/module Instantiating http://nabwgra1/public/app/plugins/datasource/gridprotectionalliance-osisoftpi-datasource/module Loading app/plugins/datasource/gridprotectionalliance-osisoftpi-datasource/module

**Comment by ritchiecarroll** [comment]
Are you sure the plug-in is installed into the plugins folder for the beta version?

**Comment by Aysha94** [comment]
Yes it is installed there in this path "public/app/plugins/datasource/gridprotectionalliance-osisoftpi-datasource/"

**Comment by Aysha94** [comment]
Any update?

**Comment by EEParker** [comment]
I am not experiencing any issues with the current version on our systems with Grafana 5. You might check that the plugin path in your grafana.ini file matches the location of the plugin.

I included screenshots of my settings for reference:

### PI WebAPI Config
![image](https://user-images.githubusercontent.com/15874076/36988274-17a55b88-2064-11e8-8063-00d5cfdcd568.png)


### Grafana Config
```ini
#################################### Paths ####################################
[paths]
# Path to where grafana can store temp files, sessions, and the sqlite3 db (if that is used)
#
;data = /var/lib/grafana
#
# Directory where grafana can store logs
#
;logs = /var/log/grafana
#
# Directory where grafana will automatically scan and look for plugins
#
;plugins = /var/lib/grafana/plugins
```


![image](https://user-images.githubusercontent.com/15874076/36988094-8665d62a-2063-11e8-8905-3e7119c8ac77.png)
![image](https://user-images.githubusercontent.com/15874076/36988121-9a4e65b2-2063-11e8-8084-1e09581b726f.png)

**Comment by Aysha94** [comment]
We were able to solve this issue. Thank you for your contribution.
