### ISSUE TITLE
Using template variables with names/paths containing spaces together with "All" fails

### ISSUE THREAD

**Issue by kristwaa** [GridProtectionAlliance/osisoftpi-grafana#115]
Investigating why a dashboard using variables failed I came across this:
```
{
  "request": {
    "url": "api/datasources/proxy/uid/Fwxkfxnxx/attributes?selectedFields=WebId%3BName%3BPath&path=<snip>\\{A1 Unit 1,A2 Unit 2,A3 Unit 3}\\<snip>",
    "method": "GET",
    "hideFromInspector": false
  },
  "response": {
    "Errors": [
      "Not found: '<snip>\\{A1 Unit 1,A2 Unit 2,A3 Unit 3}\\<snip>'. Invalid object path format for '<snip>\\{A1 Unit 1,A2 Unit 2,A3 Unit 3}\\<snip>'.\r\nParameter name: path"
    ]
  }
}
```

The plugin logic fails to replace the variable in the path if the variable values contain spaces and the user selects "All" from the dropdown:
![image](https://user-images.githubusercontent.com/3738374/223378840-5243e895-ae71-41fa-a898-e9a35057ba38.png)

Suggested fix in ~~#114~~ #116.

**Comment by coderReview** [comment]
Will appear on version 4.0.0.
