### ISSUE TITLE
Table panel don't show all values

### ISSUE THREAD

**Issue by SC-66** [GridProtectionAlliance/osisoftpi-grafana#117]
I have a simple table panel, displaying a string. But the panel don't show all values (strings). In the pic below you see that compared to the Time Series Data in Osisoft (Aveva) PI, some values. Se red marking in the example below. It should be a value at 00:05:43. When I do inspect data it is still missing. 
I'm using Grafana 9.4.1

![image](https://user-images.githubusercontent.com/92076711/224314372-d1c419fa-598b-4369-89b5-d2912f7a763a.png)

**Comment by SC-66** [comment]
When I changed From showing data for "Today" to a small time period, the all data was displayed. It was when I limit the period to 4 hours, 12 minutes 17 seconds all data was shown. All time periods above that then data was filtered out. Why is that? I want to be able to show all data for the selected time period.

**Comment by SC-66** [comment]
Solved it by changing to Recorded Values and limit to 10000 values.

**Comment by coderReview** [comment]
@SC-66 The plugin uses 3 controllers from the PiWebAPI

By default it uses: GetPlot => streams/{webId}/plot

You can used the interpolation: GetInterpolated => streams/{webId}/interpolated

And recorded: GetRecorded => streams/{webId}/recorded

Glad the last one solved your problem.
