### ISSUE TITLE
Edit panel position problem

### ISSUE THREAD

**Issue by Aysha94** [GridProtectionAlliance/osisoftpi-grafana#12]
Hello

I'm using grafana version 5.0.3 with osipi data source on windows os .
 When I try to add a new graph or any type of data representation, I get the edit panel moved up on top of the graph. in such a way it hides the graph, instead of being down under the graph

attachment shows what I mean
![edit panel](https://user-images.githubusercontent.com/36470909/38011067-6126ea58-324b-11e8-8eca-48f91f1e8653.PNG)

**Comment by EEParker** [comment]
I'm not having this issue with 5.0.0, but I will look into it.
![image](https://user-images.githubusercontent.com/15874076/38218719-62a7f83a-3698-11e8-92e1-2e103397889b.png)

**Comment by Aysha94** [comment]
![grafana_edit](https://user-images.githubusercontent.com/36470909/38233433-1131b636-370a-11e8-883e-e972d60d7144.PNG)


Error:

Possibly unhandled rejection: {"data":{"Errors":["Not found: '\\\\'. Invalid object path format for '\\\\'.\r\nParameter name: path"]},"status":404,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/datasources/proxy/5/elements?path=\\\\","headers":{"X-Grafana-Org-Id":1,"Accept":"application/json, text/plain, */*"},"retry":0},"statusText":"Not Found","xhrStatus":"complete"}

**Comment by EEParker** [comment]
On your datasource configuration screen, does the 'test' pass for the PI connector?

**Comment by Aysha94** [comment]
yes  it pass the test

**Comment by EEParker** [comment]
This might be your issue:
![image](https://user-images.githubusercontent.com/15874076/38742504-5ac5375a-3f02-11e8-9653-13e67e7307aa.png)

**Comment by coderReview** [comment]
Old issue. Closing.
