### ISSUE TITLE
Calculations attributes issues

### ISSUE THREAD

**Issue by TheFern2** [GridProtectionAlliance/osisoftpi-grafana#121]
I am not sure if there are a couple of issues here, or if is the same issue. I have been told all these calcs worked in 2.1.0 or so, but I setup 2.1.0 branch locally and calculations don't work. So I am thinking from version 1.0.0 or forward we were perhaps running a custom version in our prod server. I am also told there is no backup of whatever was running, so that I could verify locally that these calcs do in fact work.

Issue 1 for one attribute '.' dot selection works, but not using the named attribute. I get no errors in console, nor network. All status codes are 207:

Works:

![image](https://user-images.githubusercontent.com/10265682/235214812-627be3bd-c1d3-4a8d-a4cb-f27471dede55.png)

Does not work:

![image](https://user-images.githubusercontent.com/10265682/235214916-61aa0683-1545-4a4c-bf2d-2d3b68293478.png)

Issue 2 specifying attribute(s) in calculation without having it in Attributes. We have many dashboards setup like this and I have been told they worked prior to the upgrade.

Doesn't work, not even if I add attribute to attributes and use dot in the calculation. Using dot worked in my previous example but not this one.
![image](https://user-images.githubusercontent.com/10265682/235216874-4ebba406-5925-4a0a-811b-debc3e8ac037.png)

I will see what else I can dig up and post updates here. Let me know if there is any more info you need.

**Comment by coderReview** [comment]
@TheFern2 does running the PiWebAPI query directly using Postman or Insomnia work?

**Comment by coderReview** [comment]
I will look at the issues next week.

**Comment by TheFern2** [comment]
> I will look at the issues next week.

Thank you!

**Comment by coderReview** [comment]
Fixed by https://github.com/GridProtectionAlliance/osisoftpi-grafana/pull/122. Please check

**Comment by coderReview** [comment]
@TheFern2 

![image](https://user-images.githubusercontent.com/5925442/235908463-53b95198-bbd2-4e54-8a5f-e58a2dc40556.png)

- No attribute selected, calculation = '<Attribute Name>'*1.5 => **Worked**

![image](https://user-images.githubusercontent.com/5925442/235908102-6359e229-33a9-4311-bbb7-f45c605df8c7.png)

- Attribute selected, calculation = '.'*1.5 => **Worked**
- Attribute selected, calculation = '<Attribute Name>'*1.5 => **Won't work**

**Comment by coderReview** [comment]
I am making a small change:

- No checkbox selected => Will use [Calculation_GetAtTimes](https://any-api.com/osisoft_com/osisoft_com/docs/_calculation_times/Calculation_GetAtTimes)
- Recorded selected => Will use [Calculation_GetAtRecorded](https://any-api.com/osisoft_com/osisoft_com/docs/_calculation_recorded/Calculation_GetAtRecorded)
- Interpolated selected => Will use [Calculation_GetAtIntervals](https://any-api.com/osisoft_com/osisoft_com/docs/_calculation_intervals/Calculation_GetAtIntervals)
- Summary selected => Will use [Calculation_GetSummary](https://any-api.com/osisoft_com/osisoft_com/docs/_calculation_summary/Calculation_GetSummary)

For using normal arithmetics use "Recorded". For using functions with interval, using Interpolated with "${intervalTime}" variable and control using the interpolated period.

Example:
```json
TagAvg('.', '*-${intervalTime}', '*')
```

**Comment by TheFern2** [comment]
Thanks @coderReview are you saying you're making an addition change to include intervalTime using interpolated period, or that the change is made and merged into main branch?

**Comment by coderReview** [comment]
The intervalTime is already merged. I am just making the changes to meet this:

- No checkbox selected => Will use [Calculation_GetAtTimes](https://any-api.com/osisoft_com/osisoft_com/docs/_calculation_times/Calculation_GetAtTimes)
- Recorded selected => Will use [Calculation_GetAtRecorded](https://any-api.com/osisoft_com/osisoft_com/docs/_calculation_recorded/Calculation_GetAtRecorded)
- Interpolated selected => Will use [Calculation_GetAtIntervals](https://any-api.com/osisoft_com/osisoft_com/docs/_calculation_intervals/Calculation_GetAtIntervals)
- Summary selected => Will use [Calculation_GetSummary](https://any-api.com/osisoft_com/osisoft_com/docs/_calculation_summary/Calculation_GetSummary)

At the moment we have this:

- No checkbox selected or Recorded selected => Will use [Calculation_GetAtRecorded](https://any-api.com/osisoft_com/osisoft_com/docs/_calculation_recorded/Calculation_GetAtRecorded)
- Interpolated selected => Will use [Calculation_GetAtIntervals](https://any-api.com/osisoft_com/osisoft_com/docs/_calculation_intervals/Calculation_GetAtIntervals)
- Summary selected => Will use [Calculation_GetSummary](https://any-api.com/osisoft_com/osisoft_com/docs/_calculation_summary/Calculation_GetSummary)

**Comment by coderReview** [comment]
@elwills I will wait and add this feature to v4.1.0.

@TheFern2 v4.0.0 will work for you with the above considerations.

v4.1.0 will make the change described above.

**Comment by TheFern2** [comment]
Thanks for the update I think 4.0.0 works for us for now.
