### ISSUE TITLE
Some PIWEBAPI server not showing the full path of element

### ISSUE THREAD

**Issue by EduMoura-ONS** [GridProtectionAlliance/osisoftpi-grafana#130]
Hello All.

We started to use the datasource plugin with 4 API Servers for some reason i can only navigate trough elements in one of them. The configuration are the same and the user has correct access using PI explorer. 

This is the positive case (where works)
![PositiveScenario](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/138237705/a04c9f37-430f-4d6a-aaab-8a3bfa7978cb)

In a second datasource (different server) the behaviour above not happen. I tried to make a API get call using XH and it works from terminal, eliminating a possible firewall block.

I also tried to downgrade to 4.1 version without success either.

Some help?

**Comment by coderReview** [comment]
If you want to use different AF Server/Database leave the configuration below empty:

![image](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/5925442/966c0de6-60aa-40ca-bdb4-58505b39a90e)

You can also check the web browser developer console/network to catch any additional error.

**Comment by coderReview** [comment]
If you want to restrict access to only one AF server or Database, fill the configuration with the appropriate values.

**Comment by EduMoura-ONS** [comment]
It works! Thanks a lot Paulo!
The docs lead me to set the servers for my connections.

**Comment by EduMoura-ONS** [comment]
I think that docs could be more specific about que configurations.

**Comment by coderReview** [comment]
Documentation is still an item to be worked on.

**Comment by EduMoura-ONS** [comment]
How can I help?

**Comment by coderReview** [comment]
You can create a PR with updated documentation (README.md)
