### ISSUE TITLE
Version 5.0

### ISSUE THREAD

**Issue by coderReview** [GridProtectionAlliance/osisoftpi-grafana#135]
- Move to datasource plugin code
- Support alert
- Support public dashboard

**Comment by coderReview** [comment]
we are still working on it. my goal was to finish this month, but I don't think that is going to be possible.

**Comment by kristwaa** [comment]
Any development in the work on Version 5.0?

**Comment by casperth** [comment]
Is there any release date yet?

**Comment by coderReview** [comment]
If you want to try it out check the `backend` branch.

**Comment by pvmagacho-nde** [comment]
There are a few bugs yet. Should have a new version by the end of next week.

**Comment by coderReview** [comment]
@elwills https://github.com/GridProtectionAlliance/osisoftpi-grafana/pull/155 ready to merge.

**Comment by elwills** [comment]
The latest release is pending review at Grafana.
