### ISSUE TITLE
Calculation creates faulty query

### ISSUE THREAD

**Issue by alexl04** [GridProtectionAlliance/osisoftpi-grafana#138]
Grafana 10.01/10.02 [Linux]
osisoftpi Grafana plugin 4.2
osisoftpi WEB API 2022 patch 1

Issues:
1. Calculation does not work in combination with Summary Period. Issue present in all plugin versions.
2. Plugin sends an incorrect query to PI if we add a Calculation in the query. See screenshots. It seems that the dashboard time-window is divided into multiple smaller time-windows and then inserted into the query to PI. This results in a query with fewer data points than expected by the Query settings in Grafana. Issue is seen from plugin version 4+. With version 3 this was no issue.
<img width="1277" alt="wrong" src="https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/56631466/2ce8822b-c97b-48eb-a4ec-f06cf7a64080">
<img width="1273" alt="good" src="https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/56631466/a172db4c-52d8-431d-be83-b7bb3aab661b">

**Comment by complacentsee** [comment]
I believe the default value is defined as 40 calculated values in version 4 instead of being dynamically calculated.

**Comment by alexl04** [comment]
> I believe the default value is defined as 40 calculated values in version 4 instead of being dynamically calculated.
> 
> @coderReview I believe I stumbled onto both issues when testing the backend version and have the fix in there.

Awesome work! will the fix be included in the next available version?

**Comment by coderReview** [comment]
I have added a fix in version 5.0.0. It's actually defaults to recorded values.
