### ISSUE TITLE
Can't switch back to editor mode

### ISSUE THREAD

**Issue by pvmagacho-nde** [GridProtectionAlliance/osisoftpi-grafana#140]

**Comment by alexl04** [comment]
<img width="802" alt="image" src="https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/56631466/fe4ebe74-159e-4a53-bcd2-238792f64580">

**Comment by aballinEH2** [comment]
If it's a helpful data point, I think switching back to editor mode worked for me using v4.2.0 of this plugin when I was on Grafana 9.4.3, however it no longer works for me after upgrading to Grafana 10.2.3.

**Comment by coderReview** [comment]
Fixed in #150
