### ISSUE TITLE
Ability to return all attributes when using variables

### ISSUE THREAD

**Issue by cfitzw** [GridProtectionAlliance/osisoftpi-grafana#141]
When using a variable to select/set the AF structured elements (plural), not all of the attributes are returned, only the first attribute for each element is. When selecting a single element using a variable, it does return each attribute.

The use case for this in particular is building out a Geomap, where I'd like to display numerous attributes for each element when clicked upon (i.e. Make, Model, etc.)

**Comment by pvmagacho-nde** [comment]
@cfitzw we need more information/screenshots to determine the issue.

**Comment by cfitzw** [comment]
![PI_AF_Structure](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/20694057/6307cc12-33ba-432d-a464-11f2a6514f1a)
![Grafana_Variables](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/20694057/75fb9281-e8dc-4609-a8fd-d241bcdf43ad)
![Plugin_Multiple_Attributes_Working_with_Single_Variable](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/20694057/a70aa64e-b013-4dad-90f7-02248b9fad6b)
![Plugin_Multiple_Attributes_Not_Working_with_Multiple_Variables](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/20694057/dd60f7de-4f3a-4c3a-9f63-7f6194420245)

Here are screenshots of the AF structure, the variables defined for the grafana dashboard, a working example using a single variable selection which returns all attributes for the element, and finally a non-working example using multiple variables which only returns the first attribute for each element (thus, this ticket).

**Comment by pvmagacho-nde** [comment]
do you want to use multiple variables in the same graph?

**Comment by cfitzw** [comment]
@pvmagacho-nde If you mean attributes, then yes. Specifically for the built-in Geomap (plotting of all assets and allowing to click on them to see all attributes), as this currently is not working/possible.

**Comment by coderReview** [comment]
@cfitzw at the moment selecting all can only be done for one variable only. The other ones cannot have all options.
