### ISSUE TITLE
"Use Last Value" not work

### ISSUE THREAD

**Issue by peterprvy** [GridProtectionAlliance/osisoftpi-grafana#143]
When  checkbox "Use Last Value" is checked, plugin still returned "No Data"

Recorded Data when not use last value:

![image](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/36068077/91b3af52-d8aa-438f-a5cf-a179716183f7)

![image](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/36068077/8c29e27e-9c42-47f9-b8e6-f31360c3009b)

When checked "Use last value" (for first two PI Points), 

![image](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/36068077/e0906145-06b6-4bad-8a7c-603870dbe4c8)

The plugin apparently expects piwebapi to return a value at the exact time, but the last value exists before that time.

The expected behavior is that the plugin will return the last values in the given interval, that means it will use the parameter 'retrievalMode=AtOrBefore'

**Comment by coderReview** [comment]
The last value is not using recorded endpoint. It uses GET streamsets/{webId}/value, which doesn't have the above option.

**Comment by peterprvy** [comment]
@coderReview 

And it cannot be programmed, e.g. when 'Recorded Values' is checked? It is almost unlikely that if endTime === now that there will be a value for a tag at this time, the system would have to store tags every second and even then it will happen that your access for 'Last value' will return 'No Data '

Sorry, my english is bad, i am use translator

**Comment by fsbrito-dev** [comment]
@coderReview,
The lastvalue actually flashes when used in the PIAF formula.
I suggest creating an interpolation option, this way we would avoid losing values ​​involved in the formula.
