### ISSUE TITLE
Use of variable for summary period does not work

### ISSUE THREAD

**Issue by SC-66** [GridProtectionAlliance/osisoftpi-grafana#144]
I tried use a variable to specify the summary period (interval) in the query, se picture, but that doesn't work.
Or do I use it wrong?

![SummaPeriodUseVariable](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/92076711/68afcf4e-0e42-4236-8084-704344a4debf)

**Comment by coderReview** [comment]
That is not implemented.
