### ISSUE TITLE
having issue with retrieving data from PI Web API 2017 R2

### ISSUE THREAD

**Issue by zeitounomar** [GridProtectionAlliance/osisoftpi-grafana#145]
Hello and thank you for your support in advance!
My first question does this plugin support this version of PI Web Api
I can connect the data source  successfully and find the Pi Point but then no data is returned with the error below
![image](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/73667182/9172e7cf-9f40-4314-a6d1-0ecf50f7f926)

**Comment by coderReview** [comment]
The one I am using right now is PI Web API 2021 SP3. I don't have the above version to test and validate. If possible, upgrade to  PI Web API 2021 SP3 or higher.
