### ISSUE TITLE
Add new feature to use variable in Summary period for the query

### ISSUE THREAD

**Issue by SC-66** [GridProtectionAlliance/osisoftpi-grafana#146]
Please add the option to use variable in the field for Summary period in the query definition, see pic below.

![SummaPeriodUseVariable](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/92076711/80dafafc-2801-4fa2-8fda-7693ed7ebb04)

**Comment by coderReview** [comment]
Fixed in version 5.0.0
