### ISSUE TITLE
elementPath not filled in with Raw Query

### ISSUE THREAD

**Issue by alexl04** [GridProtectionAlliance/osisoftpi-grafana#147]
Grafana 10
Latest Grafana OSI Soft PI plugin version
Latest PI API

<img width="719" alt="image" src="https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/56631466/874074e8-46b2-404a-bd71-415bbbc37f9f">

**Comment by coderReview** [comment]
Can you give more details on how you use the API?

**Comment by alexl04** [comment]
> Can you give more details on how you use the API?

The elementPath is missing in the dashboard JSON Model if you add another panel with data from PI via the AF Raw Query Mode. See below example.
<img width="722" alt="image" src="https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/56631466/7f81f7e9-4a35-40fa-be20-04548c15afb3">
<img width="724" alt="image" src="https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/56631466/855d2a3f-0c71-4308-b209-8d42869cb949">


<img width="450" alt="image" src="https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/56631466/c78a93d7-8015-4592-9932-14a9aec3d34e">


This is also true if you add 2 queries into the same panel. The one generated via the AF Raw Query Mode is missing the elementPath.

**Comment by coderReview** [comment]
Fixed in PR #150
