### ISSUE TITLE
All functionality related to Grafana Osisoft-PI System Datasource is broken

### ISSUE THREAD

**Issue by TomyZacharia** [GridProtectionAlliance/osisoftpi-grafana#148]
Grafana - v 10.3.3
Data source Plugin version - 4.2.0
PI Web API version - 2023, 1.18
PI Archive version - 3.4.440

1. Data source can be created and passes connectivity testing.
2. Neither AF nor pi Points are working. Unable to query the system for discovering tags. 
3. Old dash boards do not work with pre-existing data source nor with newly created data source.
4. New Dashboards cant be created with new data source. Manually writing the tag names also doesn't work.

**Comment by pvmagacho-nde** [comment]
Hello @TomyZacharia, we haven't fully tested the plugin with the latests version 10 of Grafana. If you try with latest version 9, do you still have this issues?

**Comment by coderReview** [comment]
Will check version 10.x

**Comment by TomyZacharia** [comment]
Thanks for the prompt response. I created a new Ubuntu 22.04 VM, updated and installed Grafana 9.5.16 with GPA PI plugin 4.2. 
Once again Data Source test works.
Unable to browse pi points or AF elements in the Query dialog.. 

Yahoo Mail: Search, organise, conquer 
 
  On Mon, 4 Mar 2024 at 20:05, Paulo Vitor ***@***.***> wrote:   


Tested with latest version of 9.x and all seems to be ok

**Comment by TomyZacharia** [comment]
To answer your queries.   
   - How old was that? Version 9? Which was the previous version of the plugin? Can you share the plugin configuration? - The last time it was working was on Grafana 10.2.X and with GPA Plugin 4.2. The plugin configuration is attached as a screeenshot   

   - I was able to create a dashboard with PI AF and PI points with new datasource. What do you mean by manually writing the tag names? - Earlier i could type the first few characters of a tag name (PI Points mode in Query) and it would suggest. The same would work with PI AF elements too. Now no suggestions are visible.   
   
   

   - I saw a suggestion in the documentation regarding "proxy access setting". What is this setting and how do i configure this?   


Tomy Zacharia 

    On Monday, 4 March, 2024 at 07:46:46 pm IST, Paulo Vitor Magacho ***@***.***> wrote:  
 
 


Just downloaded version 10.3.3 of Grafana using plugin version 4.2.0

"ProductTitle": "PI Web API 2021 SP3",
"ProductVersion": "1.17.0.200",
"ServerVersion": "3.4.445.688",

If you can share the browser console error, that might be helpful.
   
   - Ok
   - I was able to create a dashboard with PI AF and PI points
   - How old was that? Version 9? Which was the previous version of the plugin? Can you share the plugin configuration?
   - I was able to create a dashboard with PI AF and PI points with new datasource. What do you mean by manually writing the tag names?

**Comment by coderReview** [comment]
I haven't had the issues shown above while running the plugin. Version 5.0.0 should be out soon.
