### ISSUE TITLE
Fix release action

### ISSUE THREAD

**Issue by coderReview** [GridProtectionAlliance/osisoftpi-grafana#151]
Hello @elwills , can you help to fix the release action? Do you have any contact with grafana to check what is needed?

**Comment by elwills** [comment]
We are working on correcting it for another plugin. As soon as we've confirmed it is functioning, I will update it here.

**Comment by pvmagacho-nde** [comment]
Thank you.

**Comment by coderReview** [comment]
Thank you

**Comment by elwills** [comment]
@coderReview the release action has been fixed, and the release is now available. I have forwarded the email from Grafana with steps to get the plugin published.
