### ISSUE TITLE
Warnings with Public Dashboard in 5.0.0-beta (c7e2c4b)

### ISSUE THREAD

**Issue by kristwaa** [GridProtectionAlliance/osisoftpi-grafana#152]
I tested the 5.0.0-beta to verify support for Public Dashboards in a local Docker instance. For some reason I got the following warnings sharing the dashboard:

<img width="545" alt="image" src="https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/3738374/aa3a1a37-d5fa-4474-87c2-985b80fd8ad6">

<img width="1280" alt="image" src="https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/3738374/74c1c71d-c7f0-42b4-924c-4fa7ddc5806d">

According to https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/#supported-data-sources:
> Public dashboards should work with any data source that has the properties backend and alerting both set to true in its plugin.json. However, this can’t always be guaranteed because plugin developers can override this functionality.

The [properties are correctly set](https://github.com/GridProtectionAlliance/osisoftpi-grafana/blob/v5.0.0-beta/src/plugin.json), so I don't know what is causing the warnings. Data seems to be returned correctly.

Sample dashboard JSON: [dashboard.json](https://github.com/GridProtectionAlliance/osisoftpi-grafana/files/15184775/dashboard.json)
Grafana version: Grafana v10.4.2 (22809dea50)

Any idea what this can be?
Have you observed this yourselves during development?

**Comment by coderReview** [comment]
Can you try with version 5.0.0?
