### ISSUE TITLE
Query Errors - v5 Beta

### ISSUE THREAD

**Issue by alexl04** [GridProtectionAlliance/osisoftpi-grafana#153]
Grafana 11
OSI plugin v5 beta
windows

Received query errors when:

1. Queried a Summary Period + Calculation
2. Queried a Calculation
![image](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/56631466/dc5f6a94-ca43-4e85-8dd7-418f308e2157)

![image](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/56631466/4f745bbc-86cb-48e9-9597-5ca9457bd880)

**Comment by pvmagacho-nde** [comment]
The plugin have not been tested in Grafana 11.

**Comment by pvmagacho-nde** [comment]
Have you tested with Grafana 10.x?

**Comment by alexl04** [comment]
> Have you tested with Grafana 10.x?

Same errors with plugin v5 beta and grafana 10.4.1

**Comment by pvmagacho-nde** [comment]
Will be corrected in v5.0.0

**Comment by coderReview** [comment]
Fixed in v5.0.0
