### ISSUE TITLE
event frame annotations: only 1 is shown

### ISSUE THREAD

**Issue by Bartkrokkie** [GridProtectionAlliance/osisoftpi-grafana#154]
Hi,

My configuration of an annotation is showing multiple events found but whatever I try, the dashboard is only showing one at the start of the graph. see below screenshots. changing the timeframe does not make a difference neither. I'm using Grafana version 9.2.8, plugin is version 4.2.0. 

what could be the issue?

regards,

Bart

![image](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/105461113/74e5e6c9-2086-4799-8bb8-978a8372c795)
![image](https://github.com/GridProtectionAlliance/osisoftpi-grafana/assets/105461113/7b11790f-3692-429a-bdde-e9dad96dc528)

**Comment by coderReview** [comment]
Please try version v5.1.0 when it's deployed. Thank you
