### ISSUE TITLE
Template variables in PiPoint queries malformed

### ISSUE THREAD

**Issue by kwekly** [GridProtectionAlliance/osisoftpi-grafana#161]
Using Grafana v11.0, osisoft-5.0.0

When I use template variables with a Pi Point, the request fails -- I think because the `label` in the payload is not expanded correctly:
![image](https://github.com/user-attachments/assets/5b220674-fe08-4d06-ac14-3d8774175f1a)

If I manually override to expand the variable with the data is returned as expected:
![image](https://github.com/user-attachments/assets/6a5125d2-d283-40d4-833c-4c830d5bef90)

**Comment by coderReview** [comment]
I am testing in 5.1.0 and can't reproduce this.

**Comment by kwekly** [comment]
ok cheers @coderReview I will get 5.1.0 deployed to our test system and confirm

**Comment by AlesLenko** [comment]
Hello, I had the same problem using the Pi Points, however I was using version 5.0.0, and after cloning and installing the 5.1.0 version locally the problem went away. I am assuming the 5.1.0 version is getting signed/approved by Grafana and will be up on public repo of Grafana plugins (please correct me if I am wrong). Hope this helps.

**Comment by kwekly** [comment]
Cheers all, I can also confirm this issue does not occur using the 5.1.0 release

![image](https://github.com/user-attachments/assets/919c44c1-1859-41be-be31-c6e829645701)
