### ISSUE TITLE
Feature request: Attribute Description as Display Name

### ISSUE THREAD

**Issue by phinduz** [GridProtectionAlliance/osisoftpi-grafana#164]
As a user I have attribute names which are not human readable, unless you are very familiar with the data.
However the attribute description is human readable and users would greatly benefit from having the option to choose this as Display Name. Would this be possible to implement?

Here is how the query currently looks like:
![image](https://github.com/user-attachments/assets/08dc3dd7-0dd6-4a13-9d35-db38fb6e4ce7)

... and here with a proposed addition of the option to use the Attribute Description as Display Name:
![image](https://github.com/user-attachments/assets/4f0226c6-e2fc-49b2-a6e8-5e3a7f72bcca)

**Comment by anders-hauglid** [comment]
I would also highly appreciate this feature!

**Comment by coderReview** [comment]
The description will be added to the new format as a label

**Comment by phinduz** [comment]
Thanks for picking up the feature request so fast @coderReview 
However, after testing 5.1.0 and looking into the code, the change hasn't been added to the GUI. Would it be possible to add it as I suggested?

**Comment by pvmagacho-nde** [comment]
You can use in the panel "Display" property using the variable ${__field.lables.description}

**Comment by phinduz** [comment]
Thanks, now it works exactly as intended! 💯
