### ISSUE TITLE
Difficulties upgrading from 5.0 to 5.1 (zip)

### ISSUE THREAD

**Issue by alexl04** [GridProtectionAlliance/osisoftpi-grafana#165]
Hi super thanks for all the work done to get a lot of the reported issues resolved in v 5.1. Appreciated big time.

Unfortunately though, I have to share that Upgrading from version 5 to 5.1 is a bit frustrating due to the manual work needed to fix all grafana panels with PI data > IF DASHBOARDS ARE IMPORTED. If the dashboard was already present and we just replace the osi-soft datasource plugin with v5.1 I don't see below issues. Complex..

Unless I am doing something wrong while importing a dashboard JSON file (Export for sharing externally) from the PRD Grafana server (grafana v11.2 and osi v5.0) into the ACC Grafana server (v11.2 and v5.1) I can report that:

1. The query settings aren't carried over (summary for x seconds for example), and when not changed manually, the Display Name of the Attribute now has '[average]' appended to the name, which causes layout settings (linked to a specific Display Name) now no longer is recognized.

2. It also seems that queries in certain panels are not transferred correctly at all but I do not yet understand the cause of it. Grafana shows NO DATA and the following ERROR is found in the CMD for grafana-system.exe

"""
ERROR[09-26|10:48:10] Error unmarshalling query                logger=plugin.gridprotectionalliance-osisoftpi-datasource error="json: cannot unmarshal string into Go struct field QuerySummary.JSON.summary.types of type plugin.SummaryType" json="{\"RefID\":\"A\",\"QueryType\":\"\",\"MaxDataPoints\":713,\"Interval\":1000000000,\"TimeRange\":{\"From\":\"2024-09-26T10:33:10.609+02:00\",\"To\":\"2024-09-26T10:48:10.609+02:00\"},\"JSON\":{\"attributes\":[{\"label\":\"Nav_String_Out-Trench_Depth\",\"value\":{\"expandable\":false,\"value\":\"Nav_String_Out-Trench_Depth\"}}],\"datasource\":{\"type\":\"gridprotectionalliance-osisoftpi-datasource\",\"uid\":\"d69473bc-53c5-4a96-9964-31e3d5adde48\"},\"datasourceId\":6,\"digitalStates\":{\"enable\":false},\"display\":\"AFT - Jetting Swords Depth\",\"elementPath\":\"PIAFPROD\\\\AF-raw\\\\D398\\\\D398 Kepware connector\\\\D398\\\\Objects\\\\AB-03\\\\Trencher\\\\RAW\",\"enableStreaming\":{\"enable\":false},\"endTime\":\"2024-09-26T08:48:10.609Z\",\"expression\":\"\",\"hide\":false,\"hideError\":false,\"interpolate\":{\"enable\":false,\"interval\":\"\"},\"intervalMs\":1000,\"isAnnotation\":false,\"isPiPoint\":false,\"maxDataPoints\":713,\"nodata\":\"Null\",\"recordedValues\":{\"enable\":false},\"refId\":\"A\",\"regex\":{\"enable\":false},\"scopedVars\":{\"__interval\":{\"text\":\"1s\",\"value\":\"1s\"},\"__interval_ms\":{\"text\":\"1000\",\"value\":1000}},\"segments\":[],\"startTime\":\"2024-09-26T08:33:10.609Z\",\"summary\":{\"basis\":\"EventWeighted\",\"interval\":\"\",\"nodata\":\"Null\",\"types\":[\"\"]},\"target\":\"PIAFPROD\\\\AF-raw\\\\D398\\\\D398 Kepware connector\\\\D398\\\\Objects\\\\AB-03\\\\Trencher\\\\RAW;Nav_String_Out-Trench_Depth\",\"useLastValue\":{\"enable\":false},\"useUnit\":{\"enable\":false},\"webid\":\"F1EmaRsXEGlfyEK2AAUnbLWqQA07xBZUbN7BGHpwBQVqemuwUElBRlBST0RcQUYtUkFXXEQzOThcRDM5OCBLRVBXQVJFIENPTk5FQ1RPUlxEMzk4IEtFUFdBUkVcT0JKRUNUU1xBQi0wM1xUUkVOQ0hFUlxSQVc\"}}"

ERROR[09-26|10:48:10] Error processing query                   logger=plugin.gridprotectionalliance-osisoftpi-datasource hide=false query="map[BatchRequest:<nil> DigitalStates:false Display:<nil> Error:map[] FullTargetPath: HideError:false Index:0 IntervalNanoSeconds:0 IsPiPoint:false Label: Nodata:<nil> Regex:<nil> Resource: ResponseData:<nil> ResponseUnits: Summary:<nil> TargetPath: UseUnit: false Variable: WebID: isStreamable:false]" RefID=A
"""

Hopefully I do something wrong or that it can be resolved in the datasource plugin.

**Comment by coderReview** [comment]
- Version 5.x is a big change in code because of the move to Go language. I wasn't able to keep compatibility with the previous versions. I had a great help from one developer to do this leap. As any open source code, any help is more than welcome.

- There have been some parameters changes from the old legacy ones that didn't make a lot of sense internally. The idea is from now on to stop any additional changes in the internal parameters. This should be the last big upgrade effort.

- The summary seems to have some issues. I am looking into it. That is not something I use a lot, so some cases might have slipped by. I am also fixing some problems in the deployment. We should have version 5.2.0 quite shortly.

**Comment by alexl04** [comment]
Ok fully understood. Thanks for the swift response. For backlog, I will keep you posted about further findings wrt this issue
