### ISSUE TITLE
Tested 5.1.0 

### ISSUE THREAD

**Issue by SC-66** [GridProtectionAlliance/osisoftpi-grafana#166]
I tested the downloadable 5.1.0 version but I don't get Summary to work. It does not work (?).
The first picture is using 4.2.0 and the second picture is the 5.1.0 version.  The third picture is the dataset.

4.2.0
![image](https://github.com/user-attachments/assets/ea1d51a2-5175-42a5-8c7e-3c1f6fd35def)

5.1.0
![image](https://github.com/user-attachments/assets/b03436f4-e066-4ad3-8cb5-f7e9c352607b)

Dataset
![image](https://github.com/user-attachments/assets/9dab8d89-8456-498e-b6b5-571ed962433c)

**Comment by SC-66** [comment]
Another example;
The source data are 6 values, ranging from 0.15 to 0.33. Sum of those 6 values is 1.264 tonne. 
The PI query summary says it is 0,0662 tonne and number of values are 21600. 

![image](https://github.com/user-attachments/assets/ea2fcf78-95e7-434c-9259-655fc5aa11b8)

**Comment by pvmagacho-nde** [comment]
@SC-66  please check the enable interval option. Also use the query inspector option to find out the exact PiWebAPI rest api call.

**Comment by SC-66** [comment]
> @SC-66 please check the enable interval option. Also use the query inspector option to find out the exact PiWebAPI rest api call.

I don't understand how to use the "Enable Interval" feature. Is there a description of what it does? Why should I use in the query? I just want the total value of the selected attribute (eventweighted) for the time period I selected in the time picker. In the post below I will share the differences in the query between 4.2 and 5.1 but it is above my competence to explain why they differ and whats wrong. Why isnt 5.1 backward compatible with 4.2?

**Comment by SC-66** [comment]
And this is the non-working 5.1.0 version with the query:
![image](https://github.com/user-attachments/assets/25a29d32-f5ee-4d2a-8945-fccf3694aab8)

{
  "request": {
    "url": "api/ds/query?ds_type=gridprotectionalliance-osisoftpi-datasource&requestId=Q111",
    "method": "POST",
    "data": {
      "queries": [
        {
          "enableStreaming": {
            "enable": false
          },
          "target": "<server>\\<database>\\Applications\\Production data\\Position\\Production Tonnage\\G56_BT1100_Tonnage;Tonnage_Hour",
          "elementPath": "<server>\\<database>\\Applications\\Production data\\Position\\Production Tonnage\\G56_BT1100_Tonnage",
          "attributes": [
            {
              "label": "Tonnage_Hour",
              "value": {
                "value": "Tonnage_Hour",
                "expandable": false
              }
            }
          ],
          "segments": [
            {
              "label": "<server>",
              "value": {
                "expandable": true,
                "value": "<server>"
              }
            },
            {
              "label": "<database>",
              "value": {
                "expandable": true,
                "value": "<database>"
              }
            },
            {
              "label": "Applications",
              "value": {
                "expandable": true,
                "value": "Applications"
              }
            },
            {
              "label": "Production data",
              "value": {
                "expandable": true,
                "value": "Production data",
                "webId": "F1EmpYXRubVugE663qaXJWcCgQuiBWJel66RGUhQBQVqtdIAUElBRlBST0QuQk9MSURFTi5DT01cQk9MSURFTi5QUk9EXEFQUExJQ0FUSU9OU1xQUk9EVUNUSU9OIERBVEE"
              }
            },
            {
              "label": "Position",
              "value": {
                "expandable": true,
                "value": "Position",
                "webId": "F1EmpYXRubVugE663qaXJWcCgQl_ZLYul66RGUhQBQVqtdIAUElBRlBST0QuQk9MSURFTi5DT01cQk9MSURFTi5QUk9EXEFQUExJQ0FUSU9OU1xQUk9EVUNUSU9OIERBVEFcQUlUSUs"
              }
            },
            {
              "label": "Production Tonnage",
              "value": {
                "expandable": true,
                "value": "Production Tonnage",
                "webId": "F1EmpYXRubVugE663qaXJWcCgQmvZLYul66RGUhQBQVqtdIAUElBRlBST0QuQk9MSURFTi5DT01cQk9MSURFTi5QUk9EXEFQUExJQ0FUSU9OU1xQUk9EVUNUSU9OIERBVEFcQUlUSUtcUFJPRFVDVElPTiBUT05OQUdF"
              }
            },
            {
              "label": "G56_BT1100_Tonnage",
              "value": {
                "expandable": true,
                "value": "G56_BT1100_Tonnage",
                "webId": "F1EmpYXRubVugE663qaXJWcCgQnfZLYul66RGUhQBQVqtdIAUElBRlBST0QuQk9MSURFTi5DT01cQk9MSURFTi5QUk9EXEFQUExJQ0FUSU9OU1xQUk9EVUNUSU9OIERBVEFcQUlUSUtcUFJPRFVDVElPTiBUT05OQUdFXEc1Nl9CVDExMDBfVE9OTkFHRQ"
              }
            },
            {
              "label": "Select Element",
              "value": {
                "value": "-Select Element-"
              }
            }
          ],
          "isAnnotation": false,
          "refId": "TotalTonnage",
          "interpolate": {
            "enable": false,
            "interval": ""
          },
          "useLastValue": {
            "enable": false
          },
          "useUnit": {
            "enable": false
          },
          "recordedValues": {
            "boundaryType": "Inside",
            "enable": true
          },
          "digitalStates": {
            "enable": false
          },
          "webid": "",
          "regex": {
            "enable": false
          },
          "expression": "",
          "summary": {
            "basis": "EventWeighted",
            "duration": "",
            "enable": true,
            "interval": "",
            "nodata": "Null",
            "sampleInterval": "",
            "sampleTypeInterval": false,
            "types": [
              {
                "label": "Total",
                "value": {
                  "expandable": true,
                  "value": "Total"
                }
              }
            ]
          },
          "nodata": "Null",
          "startTime": "2024-10-15T04:59:00.000Z",
          "endTime": "2024-10-15T09:59:59.000Z",
          "isPiPoint": false,
          "hideError": false,
          "scopedVars": {
            "__interval": {
              "text": "2s",
              "value": "2s"
            },
            "__interval_ms": {
              "text": "2000",
              "value": 2000
            }
          },
          "datasource": {
            "type": "gridprotectionalliance-osisoftpi-datasource",
            "uid": "bde3a28a-8c8a-4ffb-86c3-28a8170b7e5a"
          },
          "datasourceId": 1,
          "intervalMs": 2000,
          "maxDataPoints": 6000
        }
      ],
      "from": "1728968340000",
      "to": "1728986399000"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "TotalTonnage": {
        "status": 200,
        "frames": [
          {
            "schema": {
              "refId": "TotalTonnage",
              "meta": {
                "typeVersion": [
                  0,
                  0
                ],
                "executedQueryString": "https://<server>/PIWebapi/streamsets/summary?startTime=2024-10-15T04:59:00Z&endTime=2024-10-15T09:59:59Z&summaryType=Total&summaryBasis=EventWeighted&webId=F1AbEpYXRubVugE663qaXJWcCgQnfZLYul66RGUhQBQVqtdIAufi-20PH3FYk6fowoY4xlgUElBRlBST0QuQk9MSURFTi5DT01cQk9MSURFTi5QUk9EXEFQUExJQ0FUSU9OU1xQUk9EVUNUSU9OIERBVEFcQUlUSUtcUFJPRFVDVElPTiBUT05OQUdFXEc1Nl9CVDExMDBfVE9OTkFHRXxUT05OQUdFX0hPVVI"
              },
              "fields": [
                {
                  "name": "Time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "G56_BT1100_Tonnage|Tonnage_Hour[Total]",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1728968340000
                ],
                [
                  0.05250658573168182
                ]
              ]
            }
          }
        ],
        "refId": "TotalTonnage"
      }
    }
  }
}

**Comment by pvmagacho-nde** [comment]
This is the URL from the Summary Controller /summary?summaryType=<summary type 1>&summaryType=<summary type 2>&summaryBasis=<summary basis>[&summaryDuration=<summary duration][&sampleType=Interval&sampleInterval=<sample interval>]

**Comment by pvmagacho-nde** [comment]
Duplicated of #160
