### ISSUE TITLE
OSIsoft-PI Plugin connection issue

### ISSUE THREAD

**Issue by alqassak** [GridProtectionAlliance/osisoftpi-grafana#2]
Hi all,
I'm trying to configure the OSIsoft-PI plugin but once i click on Save & Test, a message appears "HTTP Error: Unauthorized" on IE and in Chrome I receive Success: Data source is working,

after that i try to create an annotation but the Asset Framework "AF" is empty, I've tried to debug the data source connection using Inspect on Chrome and found the following messages whenever i try to save & test the data source:

- Invalid Basic Auth Header
- GET http://GRAFANA_URL:8080/api/datasources/proxy/5/assetdatabases?path=\AF_SERVER\Grafana 401 (Unauthorized)

We are using the PI admin account as Username and Password,

What Grafana version are you using?
We are using Grafana 4.1.1

What datasource are you using?
OSIsoft-PI

What OS are you running grafana on?
Windows 2012 R2 Server

What did you do?
Creating OSIsoft-PI data source
![image](https://cloud.githubusercontent.com/assets/25760677/22945558/b75540ae-f305-11e6-89e0-89718a46c626.png)

What was the expected result?
To connect successfully
![image](https://cloud.githubusercontent.com/assets/25760677/22945576/c714226c-f305-11e6-9cc5-0bc65eccbeb8.png)

What happened instead?
We start getting Invalid Basic Auth Header and "GET http://GRAFANA_URL:8080/api/datasources/proxy/5/assetdatabases?path=\AF_SERVER\Grafana 401 (Unauthorized)"

Also sometimes we receive Success: Data source is working but when we try to get the assets from AF it show us empty elements.

**Comment by EEParker** [comment]
Hi,

What authentication methods do you have enabled for PI-WebAPI? I have only tested with anonymous and basic authentication over HTTPS. The configuration is in the AF Configuration database. Note, if it is modified to anything other than kerbos coresight will not function. We use a separate PI-WebAPI instances and servers for coresight and grafana.

**Comment by alqassak** [comment]
Hello @EEParker ,
Thanks for the support and i found the issue and it has been solved, i wish this can be added in the documentation for the Plugin Configuration,

My issue is having the PI Web API system configuration in AF database Kerberos as AuthenticationMethod "PI Web API default" instead of Basic, I've just replace it and it worked,
![image](https://cloud.githubusercontent.com/assets/25760677/22970321/c88607c8-f382-11e6-9c1a-98b059d525c5.png)

Regards,
Khalil AlQassab
