### ISSUE TITLE
Datasource Creates OK, Web API query not correct

### ISSUE THREAD

**Issue by mattgpcops** [GridProtectionAlliance/osisoftpi-grafana#21]
Hi,

I have installed the Datasource plugin and when I create a datasource it tests fine.

I can also navigate the boxes in a graph panel to find the data point in AF, however the problem is that I am not getting any data back.

When I look at the Query inspector it shows the following:

"No HTTP resource was found that matches the request URI 'https://xxxx.xxxx.com.austreamsets/plot?startTime=2018-09-21T04:25:43.236Z&endTime=2018-09-21T04:40:43.237Z&intervals=959&webid=A0EVjPDxUtQTkGQzx05tc5jRQLfMqsrxMtkyDEkVFuY3zwwehghRjbITwcQ7yMX5s-RTgR1BDTFBJT1BcR1BDT1BTIFBST0QgMVxHTEFEU1RPTkUgUE9SVFMgQ09SUE9SQVRJT05cUkdUQ1RcRE9PUCBET1pFUlxEWjI0OHxFTkdJTkUgU1BFRUQ'."

It looks like the call to the PI Web API is missing the /piwebapi/ from the end of the address. If I correct this and call the address from the Grafana server it returns data correctly.

I have tried playing around with the Datasource HTTP URL but that just makes the Save & Test fail.

Matt

**Comment by cluffja** [comment]
Hi Matt, from your message I am assuming when you “Save & Test” there is a variation that passes. You do seem to be correct that it looks like it is missing the “piwebapi” from the middle of the url. I am a little confused what the “austreamsets” bit is about. I’m not at work at the moment but I think ours looks something like this: “hostname.companyname.com/piwebapi/streamsets/plot?blahblahblah”. I’ll check later today to make certain that’s how ours looks. 

What are the settings you are running in the pi data source config?

**Comment by mattgpcops** [comment]
Thanks for getting back to me. Brilliant datasource btw. Grafan is so much nicer than Processbook !

The "austreamsets" is the the end of the URL ".au" with the PI API call "streamsets" tacked straight on to the end of it. Well that is what it looks like to me :)

Here is a screenshot of how I have the Datasource configured:
![image](https://user-images.githubusercontent.com/43463094/45985819-6585ac80-c0ab-11e8-83c0-f0b6b26cb364.png)

**Comment by cluffja** [comment]
Hi Matt, I cannot actually take credit for the datasource. I'm not one of the current contributors; just a friendly neighbor that likes the datasource and enjoys helping. 

This might sound ridiculous, but in your configuration under the HTTP area under the URL, try adding a forward slash "/" after "...com.au/piwebapi". We had an issue that resolved by adding that.

**Comment by cluffja** [comment]
Also, do you not have authorization in your webapi? In webapis that I've seen before they have a "Basic Auth" and then that presents a username and password field. My guess is it does. Have you tried taking your URL into a web browser and dropping it there to test as well? That will tell you if you need authorization (probably).

**Comment by mattgpcops** [comment]
Yes I have tried adding the trailing slash previously and it didn't help. It has the same issue unfortunately.

At the moment I don't have authorisation on the webapi. I thought that enabling it might just an extra layer of complication to getting things working. I have actually tried enabling authorisation and still had the same issues.

Thanks for your suggestions/help @cluffja . Maybe it is time I started working through the code.

**Comment by cluffja** [comment]
Darn. I was hoping it would be something simple like that. What version of Grafana are you running? The latest? 

This is all very weird because in order to navigate the element tree you have to utilize the PIWebAPI, so we know it's working to a degree. Maybe it's a permissions thing in your PIWebAPI. We were having issues with that yesterday and realized it was because some of the PI services were being run as local users instead of service accounts that had admin privileges.

**Comment by mattgpcops** [comment]
I am running the latest version of Grafana.

I agree, the call to get the AF element tree must work. It seems that it is just the query that is generated after that to get the actual data that is the problem. 

Thanks again @cluffja. I will just work through the problem or give it away. I thought I would post here in case I was doing something obvious that was wrong.
