### ISSUE TITLE
Updated Grafana repository version

### ISSUE THREAD

**Issue by rexc** [GridProtectionAlliance/osisoftpi-grafana#26]
Hi, is this the correct place to ask if are there any plans for an updated plugin to be pushed to the grafana repository as 1.0.3 was uploaded there over a year ago.

There seems to have a number of fixes that have come back into here source most notably one from https://github.com/cluffja/osisoftpi-grafana-datasource concerning 'average' value calls to the PIWebAPI.

This is what is currently up in the Grafana repository: 
https://grafana.com/api/plugins/179/versions

**Comment by rexc** [comment]
Thanks Ritchie, we're trying drive our Grafana setup entirely from code so pulling from repositories is ideal compared to maintaining plugin folders with zips.

**Comment by rexc** [comment]
I forgot ask, is there a timeframe to expect this in?

**Comment by EEParker** [comment]
Updated code 095993cd42cd81d562cd635569392592864872d1

**Comment by ritchiecarroll** [comment]
Thanks @EEParker, FYI, pull request to Grafana is active:
https://github.com/grafana/grafana-plugin-repository/pull/369
