### ISSUE TITLE
No data points when adding query, Status: 404 "No HTTP resource was found..."

### ISSUE THREAD

**Issue by derjuscar** [GridProtectionAlliance/osisoftpi-grafana#28]
I am having an issue pulling in data points from my PI database. 

Grafana appears to be able to see the database, as in the second photo you can see that I have the elements and attributes selected.

When I open the Query Inspector, the request still shows localhost:8080 rather than pulling from the PI database and the response is a Status: 404 with a message "No HTTP resource was found that matches the request URI..."

Any help on the issue would be greatly appreciated!

![Data_Sources](https://user-images.githubusercontent.com/52676784/60837343-ce429f00-a17c-11e9-8c3a-41ff398a922b.png)

![q](https://user-images.githubusercontent.com/52676784/60837358-d8649d80-a17c-11e9-9617-70194359c606.png)

**Comment by cluffja** [comment]
Hmm... I've seen this issue before but I'm trying to remember what the solution was. 

1. So to be clear, the URL is not localhost:8080, correct?
2. Double and triple-check your username and password. Try them in a browser to make certain that they function by navigating through the PI WebAPI.
3. Try taking the 's' off of your URL for the secure option, just to check if you need it. Sometimes if it's not configured it can freak. But I suspect you'll need it. 
4. It's possible that there needs to be a change to your PI AF config settings. We had an issue that needed this change in our servers. I'll need to ask our techs what the change was.

**Comment by derjuscar** [comment]
1. Yes, Pi Server URL is not localhost:8080,  localhost:8080 is the location of Grafana on my computer

2. I verified the username and password within the browser and also had another admin input his username and password to double check. 

3. I tried taking of the 's' from the URL, but when I click Save & Test, it gives me an "HTTP Error Not Found," so I need the 's' 

4. Within our PI database: "AuthenticationMethods": [
    "Kerberos",
    "Basic"
  ] 
  Unless there are other config settings that could be an issue?

Thanks for your help!

**Comment by dalethomas81** [comment]
@derjuscar, did you ever find a resolve for this? I am having the exact issue.

**Comment by nitinkumartech** [comment]
@derjuscar Did you ever resolve this? We are facing the same issue.

**Comment by EEParker** [comment]
Is this just an issue with localhost as the server? Perhaps try using the loopback IP address (127.0.0.1).

**Comment by lowreno** [comment]
Dear @derjuscar / @nitinkumartech !

    Do you have any fix about this problem? .... I am getting exacly the same problem...

![image](https://user-images.githubusercontent.com/7740751/88015620-030b6500-caf8-11ea-9769-81f066f03061.png)

     Thanks!
Lowreno.

**Comment by nitinkumartech** [comment]
@lowreno I was able to fix this issue. I'll raise a PR for the fix. Thanks!

**Comment by coderReview** [comment]
Didn't see any PR. Also we have new plugin framework. See #62.
