### ISSUE TITLE
Datasource issue

### ISSUE THREAD

**Issue by alqassak** [GridProtectionAlliance/osisoftpi-grafana#3]
Hi,
when I try to add a metric from AF datasource:
![image](https://cloud.githubusercontent.com/assets/25760677/23099113/576ee79e-f670-11e6-8dd4-8b37d59bafdb.png)
![image](https://cloud.githubusercontent.com/assets/25760677/23099150/54f65730-f671-11e6-8fe0-15f8accf325e.png)

In the element the plugin add's select metric
![image](https://cloud.githubusercontent.com/assets/25760677/23099134/c91493c6-f670-11e6-889d-2809dc5d517a.png)

when I remove the select metric in the toggle edit mode
![image](https://cloud.githubusercontent.com/assets/25760677/23099143/173e8d54-f671-11e6-9787-6d0b85a9b710.png)

and then add the element again
![image](https://cloud.githubusercontent.com/assets/25760677/23099148/48b9ed9c-f671-11e6-88b3-f3dae609fbb2.png)

It will work
![image](https://cloud.githubusercontent.com/assets/25760677/23099154/7b05cc80-f671-11e6-953e-9e8a365118ce.png)

When ever i need to edit a dashboard i have to do all these steps again because once you click on metrics its going to be reset and will show the value as N/A

Thanks,
Khalil

**Comment by alqassak** [comment]
Hi,
this same issue is causing IE not to display the reading from the datasource, I've mentioned it in Grafana Group and Torkel told me that it's datasource issue, here is the link to the conversation https://groups.io/g/grafana/topic/internet_explorer_ie_issue/4401818?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,4401818

> Hi,
We can see data in Chrome but we don't see it in IE

example:
![image](https://cloud.githubusercontent.com/assets/25760677/23172320/71fc6cc4-f866-11e6-80ef-8e53dc2cd74b.png)

the above screenshot is from chrome
![image](https://cloud.githubusercontent.com/assets/25760677/23172328/77ddbb2a-f866-11e6-8794-18ef6c484f8e.png)

IE screenshot
![image](https://cloud.githubusercontent.com/assets/25760677/23172335/7d73de02-f866-11e6-824f-e2fcf9f6a523.png)

also, if I login as admin in chrome it will reflect directly and will give me access to edit and add new display but in IE, I see the admin menu but when clicking on the singlestat to edit, the edit button doesn't appears,

Please note that I'm using IE version 11
Thanks,
Khalil

> Can you open IE developer tools and check for error in js console?
Think IE 11 could be a bit too old, there are some open issues with Ie 11. You will l have better luck with  Edge, chrome and Firefox. 

Cheers 
Torkel 

> Hey Torkel,
This is the error that i'm receiving in the console,
![image](https://cloud.githubusercontent.com/assets/25760677/23172526/116bf32e-f867-11e6-8afe-d48b3ada1b77.png)

Regards,
Khalil

> Strange, it's not a Javascript issue but the datasource request returns an error. 
/Torkel

**Comment by alqassak** [comment]
Dear @EEParker / @ritchiecarroll ,
Could you please help me with the above,

Thank you so much,

Regards,
Khalil AlQassab

**Comment by ritchiecarroll** [comment]
Does this work in Chrome?

**Comment by EEParker** [comment]
I do not have a solution for this at the moment, however I am looking into the issue.  Can you send a screenshot of your PI datasource connection settings? Please black out server names.

**Comment by alqassak** [comment]
![image](https://cloud.githubusercontent.com/assets/25760677/23544414/f5ad4752-0007-11e7-8d2c-b4dbf8909012.png)
![image](https://cloud.githubusercontent.com/assets/25760677/23544442/139d018a-0008-11e7-9d18-6031293a7b16.png)

We are using Grafana 4.1.1

**Comment by alqassak** [comment]
![image](https://cloud.githubusercontent.com/assets/25760677/23544523/6e830ac2-0008-11e7-9eef-269e76a6c7fc.png)

![image](https://cloud.githubusercontent.com/assets/25760677/23544502/570bfec6-0008-11e7-9bfb-43dcd3f92b4e.png)

We are using Grafana 4.1.1

**Comment by RobertZomborszki** [comment]
Hi, I've just started to use Grafana and this PI plug-in, and this issue is making problems for me too.

If I use the metrics configuration pane the "select metric" is also end up in the AF element path:
Gas\California\PW01\select metric|dGasVolume  and of course the PI WebAPI cannot find the attribute.

**Comment by EEParker** [comment]
https://github.com/GridProtectionAlliance/osisoftpi-grafana/commit/d6fd5e0cd8a2fbdf84163a20f75f80e6948e060a has some updates that might fix this issue. The plugin on Grafana website should be updated shortly, or you can try using the contents of the distribution folder here:  https://github.com/GridProtectionAlliance/osisoftpi-grafana/tree/master/dist

**Comment by alqassak** [comment]
@EEParker 

I've tried the updates and it didn't work,
with the updates I cannot read anything from PI as well when creating a new Graph in a display the selection for the element and metric they disappear,
![capture](https://cloud.githubusercontent.com/assets/25760677/25310710/5304558a-27f4-11e7-998b-ca7ed6e1df7b.PNG)

**Comment by alqassak** [comment]
Dear @EEParker

Any update?

Regards,

**Comment by alqassak** [comment]
@EEParker 
It's been a while since your last response, is there any update regarding the mentioned issue?

**Comment by rtmaster** [comment]
hi @ritchiecarroll 
have you guys tried the plugin when running grafana on https? Any particular setting is needed?
We are getting a 403 error
Thanks a lot

**Comment by ritchiecarroll** [comment]
I've not tried the OSI plug-in on HTTPS, maybe @EEParker has... I'll see if I can get it working when I get back to the office...

**Comment by rtmaster** [comment]
What looks like from our tests is that it works with PI Web Api 2016 but on PI Web Api 2017 it breaks in https mode

**Comment by EEParker** [comment]
We are currently using PI WebAPI 2017 (part of PI Vision) over HTTPS. I'm not sure if this will help, but perhaps some of these settings may help your issue.

Here are some screenshots of our configuration:

- **AuthenticationMethods**: Basic, Kerberos
- **CorsExposedHeaders**: Allow,Content-Encoding,Content-Length,Date,Location,Access-Control-Allow-Origin,Access-Control-Allow-Headers
- **CorsHeaders**: accept,authorization,content-type,origin,Access-Control-Request-Origin,Access-Control-Request-Headers,X-PIWEBAPI-HTTP-METHOD,X-PIWEBAPI-RESOURCE-ADDRESS,requestverificationtoken,x-requested-with
- **CorsMethods**: GET,POST,PATCH,OPTIONS
- **CorsOrigins**: * 

Note: CorsOrigins * is for testing. Use real servers preferred.

![image](https://user-images.githubusercontent.com/15874076/31147453-9ce53346-a84f-11e7-84b2-bc517dd9c686.png)

![image](https://user-images.githubusercontent.com/15874076/31147373-50cd67c6-a84f-11e7-8a49-db92e8131ecb.png)

**Comment by alqassak** [comment]
Dear @EEParker / @ritchiecarroll 

We were able to fix the issue's above by modifying the query_ctrl files, 

In the files "osisoftpi-grafana-master\dist\query_ctrl.js" and "osisoftpi-grafana-master\dist\query_ctrl.js.map" 
**This statement**
`_this.target.target = _this.target.target || 'select element';`
 **Was replaced with**
`_this.target.target = _this.target.target || ‘;';`

In file osisoftpi-grafana-master\dist\query_ctrl.js  
**This statement** 
`ctrl.segments = ctrl.segments.splice(0, fromIndex);
                  if (ctrl.segments[ctrl.segments.length - 1].expandable) {
                    ctrl.segments.push(ctrl.uiSegmentSrv.getSegmentForValue(null, "Select AF Database"));
                  }`
**Was replaced with**
`ctrl.segments = ctrl.segments.splice(0, fromIndex+1);
                  if (ctrl.segments[ctrl.segments.length - 1].expandable) {
                    ctrl.segments.push(ctrl.uiSegmentSrv.getSegmentForValue(null, "Select AF Database"));
}`

And osisoftpi-grafana-master\dist\query_ctrl.js.map
**This statement** 
`ctrl.segments = ctrl.segments.splice(0, fromIndex)\n          if (ctrl.segments[ctrl.segments.length - 1].expandable) {\n            ctrl.segments.push(ctrl.uiSegmentSrv.getSegmentForValue(null, \"Select AF Database\"))\n          }\n`
**Was replaced with**
`ctrl.segments = ctrl.segments.splice(0, fromIndex+1)\n          if (ctrl.segments[ctrl.segments.length - 1].expandable) {\n            ctrl.segments.push(ctrl.uiSegmentSrv.getSegmentForValue(null, \"Select AF Database\"))\n          }\n`
