### ISSUE TITLE
Alerts management

### ISSUE THREAD

**Issue by eddyrene** [GridProtectionAlliance/osisoftpi-grafana#30]
The plugins it isn't working with the alerts module of grafana. How can be fixed this? 

"tsdb.HandleRequest() error Could not find executor for data source type: gridprotectionalliance-osisoftpi-datasource"

Thank you

**Comment by clackner-gpa** [comment]
Unfortunately the OSIsoft-PI datasource does not support alarming functionality through Grafana.
There is a small number of specific Grafana datasources that support alarming functionality (https://grafana.com/docs/grafana/latest/alerting/rules/#execution). At the moment we do not gave ay plans of supporting Alerts in this data-source.

**Comment by coderReview** [comment]
Duplicated issue - https://github.com/GridProtectionAlliance/osisoftpi-grafana/issues/70
