### ISSUE TITLE
Plug-in is incompatible with string data types

### ISSUE THREAD

**Issue by b-en-nui** [GridProtectionAlliance/osisoftpi-grafana#34]
There is no way to visualize a string tag in symbols like SingleStat and Table (which would be helpful in creating certain dashboards).

**Comment by lowreno** [comment]
The same problem. I'am using Grafana 7.x. Is it possible to retrieve string/text values from piaf ? Thanks in advance.

**Comment by coderReview** [comment]
@b-en-nui can you provide an example of the data structure.
For instance: Items.Value.Value = "On"

**Comment by jonaspolfliet** [comment]
No update yet? on this topic? Still have problem query string/text values.

**Comment by coderReview** [comment]
can you provide example as requested above?

**Comment by jonaspolfliet** [comment]
![image](https://user-images.githubusercontent.com/55767937/102978104-47b28680-4504-11eb-968e-aecc35038f35.png)
Hi see picture of explorer query, normal the columns should EorW and NorS should reply a string value.

**Comment by hldiniz** [comment]
@coderReview, I'm with having the same issue. Grafana will not pull data where datatypes are string or bool. In case of bool, my way around is to convert data to int, and for strings I convert each char into ASCII then map it back in the dashbord (doesn't work for all case scenarios). Please see below in the AF tree an attribute of type string, I would like to pull it into the dashboard and display in a Discrete plot.
![discreteplot](https://user-images.githubusercontent.com/16743950/107733339-c4f4bd80-6d35-11eb-9a6b-2f3e2ff10fff.png)
![stringdtype](https://user-images.githubusercontent.com/16743950/107733466-143aee00-6d36-11eb-8b83-4a1ecbe9d01d.png)

**Comment by SC-66** [comment]
Great! Do you know approximately when 2.0.0 will be released?

**Comment by SC-66** [comment]
> We have created a new branch for it. You are all free to test and contribute. But I would say that in 1-2 months from now.

Is 2.0 close to release now?

**Comment by KRod-dmda** [comment]
Hello following up on the release of 2.0?

**Comment by coderReview** [comment]
Please continue testing and providing feedback

**Comment by KRod-dmda** [comment]
Is this the same release downloaded from the Grafana site?

**Comment by coderReview** [comment]
No. You have to manually install the plugin

**Comment by coderReview** [comment]
Download the zip file from the branch. Unzip in your `grafana/plugins` folder. Restart grafana.

**Comment by coderReview** [comment]
Fixed in v2.0.0-beta
