### ISSUE TITLE
Upgrade to support Granafa 7.x

### ISSUE THREAD

**Issue by coderReview** [GridProtectionAlliance/osisoftpi-grafana#35]
Is this plugin still maintained?

Any changes needed to support Grafana 7.x?

**Comment by ritchiecarroll** [comment]
It is maintained - slowly, as time permits. I am not aware of any changes needed for Grafana 7...

**Comment by coderReview** [comment]
hi @ritchiecarroll thank you for the response. Hope you can release the latest PRs.

**Comment by ritchiecarroll** [comment]
Oh, you just want latest code pushed up to Grafana for release? I'll get this on the to-do list.

Thanks!
Ritchie

**Comment by coderReview** [comment]
see issue #38
