### ISSUE TITLE
Grafana 7.x PI Web API AF Query Builder Element Selector Problem

### ISSUE THREAD

**Issue by pgrider** [GridProtectionAlliance/osisoftpi-grafana#38]
Starting with Grafana 7.x, the interaction between Grafana query builder and the PI Web API datasource plug-in is a little bit broken, it's almost as if Grafana 7.x is presenting data to the plugin a little bit differently and the plugin has lost its place.  Data retrievals are not affected, the issue occurs only when trying to build a new query.

Hopefully these screenshots illustrate the issue.

If you choose a PI Web API Grafana Datasource, your query window will look like this:
![Capture1a](https://user-images.githubusercontent.com/8465682/91316283-a3ebe080-e786-11ea-898f-97135e9571e9.png)

![Capture1b](https://user-images.githubusercontent.com/8465682/91316304-a817fe00-e786-11ea-8039-5ae0f5d87ffc.png)

![Capture2](https://user-images.githubusercontent.com/8465682/91316519-e6152200-e786-11ea-8d09-e9c28cb286fe.png)

![Capture3](https://user-images.githubusercontent.com/8465682/91315080-3db28e00-e785-11ea-83fe-36356f72fa33.png)

![Capture4](https://user-images.githubusercontent.com/8465682/91315077-3d19f780-e785-11ea-957c-d0104761e875.png)

The user can work around the issue by re-selecting the previous selection, this seems to force a new 'Select AF Element' button to appear.  But, this is cumbersome when working with an element tree that is nested many levels deep.

When you reach an element that has no child elements, the new button text will read 'Select AF Database', so there's been some change in Grafana 7.x that is causing some confusion with the PI Web API plug-in.
![Capture5](https://user-images.githubusercontent.com/8465682/91319915-efa08900-e78a-11ea-9211-b152fc4c3cc3.png)

This issue does not seem to occur on the Attribute row of the query builder.

**Comment by coderReview** [comment]
This seems to be some update issue. When you wait for a few seconds the button appears again.

**Comment by coderReview** [comment]
Fixing when moving to new plugin framework. See https://github.com/GridProtectionAlliance/osisoftpi-grafana/pull/62
