### ISSUE TITLE
Windows domain authentication

### ISSUE THREAD

**Issue by ikrush** [GridProtectionAlliance/osisoftpi-grafana#4]
Is there any way to connect using a Windows Domain User? We can't enable basic authentication on our server.

**Comment by EEParker** [comment]
We use the basic authentication over HTTPS and it still uses AD accounts.  If your clients have access to the WebAPI server, you might try using direct access and checking the "with credentials" box. However, this has not been tested.

![image](https://cloud.githubusercontent.com/assets/15874076/24971155/87656d26-1f7c-11e7-8888-3ffec960c2c1.png)

**Comment by ikrush** [comment]
How should I configure the datasource? We are using Windows authentication.
[API_CONFIGURATION.txt](https://github.com/GridProtectionAlliance/osisoftpi-grafana/files/950650/API_CONFIGURATION.txt)

**Comment by EEParker** [comment]
I did some internal testing and I was unable to get windows auth/kerberos working on our system.

However, based on the PI WebAPI documentation, I believe you will have to enable CORS and CorsSupportsCredentials along with adding POST to CorsMethods. Additionally, you may have to enable the ability to WRITE from CORS to get the bulk data commands working.

See: https://livelibrary.osisoft.com/LiveLibrary/content/en/web-api-v5/GUID-D0AF8333-3E78-4F4F-A233-4794DD71819C

**Comment by sidneykia** [comment]
We use OSIsoft PI data sources. In order to implement data level security, we need to use Kerberos authentication which does not appear to be currently supported in Grafana.

Is anyone able to provide me with any alternatives or insights, as our eventual aim is to implement a SSO solution in which users are defined and authenticated in Active Directory and are not required to log into Grafana.

**Comment by ritchiecarroll** [comment]
We do this today with the openHistorian by using the openHistorian web interface as a reverse proxy to Grafana. The openHistorian service actually launches Grafana and controls its lifetime with its own. Users log in through openHistorian and openHistorian automatically synchronizes users and roles with Grafana.

https://github.com/GridProtectionAlliance/openHistorian

A similar solution may work for you...

**Comment by sidneykia** [comment]
@ritchiecarroll 
Thanks for your input – most appreciated. We will have a look into this

**Comment by coderReview** [comment]
Duplicated issue 
(https://github.com/GridProtectionAlliance/osisoftpi-grafana/issues/25)
