### ISSUE TITLE
Query PI Points Directly

### ISSUE THREAD

**Issue by cluffja** [GridProtectionAlliance/osisoftpi-grafana#43]
I have been thinking about extending the plugin to allow the capability to query PI Points directly without the need for building an Asset Framework. I don’t know if “Issues” is the best place to submit this “question” or request; but I thought I would ask before beginning my work if this feature existed already but I simply have not been able to figure out how to make it work. If that was the case I would just submit a PR for doc improvement and call it a day. 

Again, apologies if this already exists and I’m too ignorant to figure it out.

**Comment by coderReview** [comment]
hi @cluffja. try looking at https://techsupport.osisoft.com/Documentation/PI-Web-API/help/controllers/point.html

**Comment by cluffja** [comment]
Yeah, I was looking at that. I think I just found what I needed. The piece of code seems to be in the QueryCtrl in the getSegmentPathUpTo function. I think this will work. Seems our server is limiting connection directly to the PI Dataserver. I’m going to close this issue for now. Thanks @coderReview  for trying to help. Once I get this working I’ll submit a PR to help improve the docs for this.

**Comment by cluffja** [comment]
Hi @coderReview, I think I may have found the issue here. The only code to distinguish between a query to the asset server and the data server is this section found in the `getWebId()` method found in `datasource.js`:

` var isAf = target.target.indexOf('\\') >= 0`

The problem I find is that there is no distinguishing way in the GUI to enter in a dataserver request without the query auto appending `\\` to the call. Leaving the element field blank returns 
![image](https://user-images.githubusercontent.com/18009131/106324877-83491a80-623f-11eb-88c0-32443ba20f80.png)

So unless I'm missing something we need to add a means to either prohibit this, improve the detection for the `isAf` variable, or make a deeper change to allow searching the dataserver. 

It's possible that the code does allow for this and I still haven't found it. In that case it's hidden in some completely non-intuitive method. Thoughts?

**Comment by coderReview** [comment]
@cluffja can you try to explain what data are you trying to fetch?

**Comment by cluffja** [comment]
Sure thing! Sorry I'm not more clear. 

So using the osisoftpi-grafana plugin in Grafana requires the creation of an Asset Framework within PI in order to query data. Basically you build your query using the Element field in the plugin to select the "path" in the AF until you find the specific attribute you would like to trend. 

We would like to be able to query data directly from the PI Point without the need to build the Asset Framework with attributes that map to the PI Points. So for instance say I have a PI Point in my Data Server called `equipment_speed` and my Data Server is simply called `myBusinessDataServer`. The actual PI Point in the Data Server would look like this:

`\\myBusinessDataServer\equipment_speed`

I'd like to be able to enter `\\myBusinessDataServer\equipment_speed` in Grafana and trend data directly without the need to build the AF. Does that make more sense?

It seems like the plugin quite nearly has this capability but turns itself off at some point.

**Comment by coderReview** [comment]
got it.

**Comment by cluffja** [comment]
Just added a pull request that hopefully resolves this issue

**Comment by cluffja** [comment]
I just found a bug where if you exit out of the panel and then come back in it drops the query. I need to debug that before we merge this.

**Comment by coderReview** [comment]
hi @cluffja. thanks. Will check also,

**Comment by cluffja** [comment]
@coderReview , I just pushed a correction to the PR that should resolve the bug I was seeing.

**Comment by txjmb** [comment]
Definitely need this too.  Anyone ready to merge it?

**Comment by coderReview** [comment]
hi @txjmb I will look later this month

**Comment by txjmb** [comment]
Thank you.  In the meantime, I'll just use the PR.

**Comment by txjmb** [comment]
Any progress on this?

**Comment by ritchiecarroll** [comment]
Hi I am just going merge this for now :-)

**Comment by ritchiecarroll** [comment]
Can the pull request be adjusted? It cannot currently be merged.

Thanks!
Ritchie

**Comment by txjmb** [comment]
It looks like this was commited here:  https://github.com/GridProtectionAlliance/osisoftpi-grafana/commit/42a420e1d592ed326ab8a65ac0426c3ab8d74d68 , is that correct?  Can we close this request?

**Comment by coderReview** [comment]
Closed by #62
