### ISSUE TITLE
Query question

### ISSUE THREAD

**Issue by sandumarius** [GridProtectionAlliance/osisoftpi-grafana#46]
Good afternoon,
How can I query the Name attribute which is a Digital State created and not value? I tried with different syntax but is not working
I do not have problems with int/float values because in that cases the value attribute is the one to read.
Thank you!

![Capture](https://user-images.githubusercontent.com/43808909/113861145-8a485800-97af-11eb-8725-4e48fbbdaf67.PNG)

**Comment by FCCMac** [comment]
I may not be understanding correctly, but I think what you're getting at is being able to represent the digital states as text. Using your example, where the value is 1 you would like to see "Local" and if it is 0 you would like to see "Hand".

If that's correct, then you can use value mappings in the "Field" tab at the right:

![image](https://user-images.githubusercontent.com/25341060/117480348-b7a73380-af1e-11eb-8c39-aef28cc42782.png)

Now your visualization will show a text representation of the digital state:

![image](https://user-images.githubusercontent.com/25341060/117480753-3bf9b680-af1f-11eb-8e42-972b1c188134.png)

If you're actually looking to grab the "Name" field and use it somewhere, you could use some creative transformations on the "Transform" tab next to the query. As data structures vary, I can't really give you a good example of this.

Hope this helps!
CM
