### ISSUE TITLE
Bad Gateway Error

### ISSUE THREAD

**Issue by AlkarimSamji** [GridProtectionAlliance/osisoftpi-grafana#48]
Hello - the data source isn't working for me as it results in a HTTP 502 error when trying to test the data source. I struggled with this issue for a while, and then had given up but suddenly the data source started working for a brief period. Now, it does not work again. 

PI Web API:
-Local on the same machine as Grafana
-I had it running on port 443 with anonymous, basic, and kerberos authentication configured. I tried changing the port to 442 for kicks as well but it did not help
-CorsOrigins = https://localhost,http://localhost,http://localhost:442,http://localhost:3000
-CorsMethods = GET,OPTIONS,POST,PUT,PATCH
-CorsHeaders = accept,content-type,requestverificationtoken,x-requested-with
-AuthenticationMethods = Kerberos, Basic, Anonymous

Data Source Settings:
-URL = https://localhost:442/piwebapi
-Access = Server (default)
-PI Server = localhost
-AF Server= localhost
-Default DB = myAFDB

When I hit "Save and Test" it results in a Bad Gateway Error

Here's what the Grafana log says:
t=2021-08-25T18:22:30-0600 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/ status=502 remote_addr=[::1] time_ms=22 size=0 referer=http://localhost:3000/datasources/edit/O-2gl0g7k
t=2021-08-25T18:22:30-0600 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/assetservers remote_addr=[::1] referer=http://localhost:3000/datasources/edit/O-2gl0g7k error="http: proxy error: read tcp 127.0.0.1:64279->127.0.0.1:442: wsarecv: An existing connection was forcibly closed by the remote host."
t=2021-08-25T18:22:30-0600 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/assetservers status=502 remote_addr=[::1] time_ms=124 size=0 referer=http://localhost:3000/datasources/edit/O-2gl0g7k
t=2021-08-25T18:22:30-0600 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/dataservers remote_addr=[::1] referer=http://localhost:3000/datasources/edit/O-2gl0g7k error="http: proxy error: read tcp 127.0.0.1:64281->127.0.0.1:442: wsarecv: An existing connection was forcibly closed by the remote host."
t=2021-08-25T18:22:30-0600 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/dataservers status=502 remote_addr=[::1] time_ms=124 size=0 referer=http://localhost:3000/datasources/edit/O-2gl0g7k
t=2021-08-25T18:22:30-0600 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/assetdatabases remote_addr=[::1] referer=http://localhost:3000/datasources/edit/O-2gl0g7k error="http: proxy error: read tcp 127.0.0.1:64280->127.0.0.1:442: wsarecv: An existing connection was forcibly closed by the remote host."
t=2021-08-25T18:22:30-0600 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/assetdatabases status=502 remote_addr=[::1] time_ms=124 size=0 referer=http://localhost:3000/datasources/edit/O-2gl0g7k

PI Web API is fully up and running and functional. I can test it from the web browser just fine. In fact, if I look at the log message above, the last path it tries to get is the /api/datasources/proxy/1/dataservers. I opened a web browser tab and hit http://localhost:3000/api/datasources/proxy/1/dataservers and it works fine - I am presented with a list of data servers .

Not sure what is the cause of this and why it started working for a short term. I have other web services running locally, including one on port 8002 and they all work fine, including my local InfluxDB, SQL Server connections. Just the OSIsoft PI one has issues.

Any help would be appreciated and if there are any questions please let me know.

Thank you!

**Comment by coderReview** [comment]
Can you make a direct request to your PI Web API using Postman or Curl?

**Comment by AlkarimSamji** [comment]
Hello,

Yes I can make a request to PI Web API using Postman and by opening a tab
on the browser.

Here is what I see in Chrome debug tools:

   1. Request URL:

      https://localhost:3000/api/datasources/proxy/1/dataservers?name=localhost
      2. Request Method:
      GET
      3. Status Code:
      502 Bad Gateway
      4. Remote Address:
      [::1]:3000
      5. Referrer Policy:
      strict-origin-when-cross-origin
      1. Response HeadersView source
      1. Content-Length:
      0
      2. Date:
      Fri, 17 Sep 2021 23:04:38 GMT
      3. X-Content-Type-Options:
      nosniff
      4. X-Frame-Options:
      deny
      5. X-Xss-Protection:
      1; mode=block
      2. Request HeadersView source
      1. accept:
      application/json, text/plain, */*
      2. Accept-Encoding:
      gzip, deflate, br
      3. Accept-Language:
      en-US,en;q=0.9
      4. Connection:
      keep-alive
      5. content-type:
      application/json
      6. Cookie:
      ajs_user_id=%224abc7534-7926-5e66-aefe-1f33ad936d48%22;
      ajs_anonymous_id=%224df5cc91-f7f4-48a2-8392-5c290f9f5172%22;
      _xsrf=2|c8d92b5b|c4cec0981ac11142a00888bbd9e8f660|1631916637;
      _hp2_id.1823968819=%7B%22userId%22%3A%22347312830041786%22%2C%22pageviewId%22%3A%223649948507549844%22%2C%22sessionId%22%3A%223714706968458747%22%2C%22identity%22%3A%224abc7534-7926-5e66-aefe-1f33ad936d48%22%2C%22trackerVersion%22%3A%224.0%22%2C%22identityField%22%3Anull%2C%22isIdentified%22%3A1%7D;
      grafana_session=56d1272a3a38a4389b9e5c14ca1919b8
      7. Host:
      localhost:3000
      8. Referer:
      https://localhost:3000/datasources/edit/O-2gl0g7k
      9. sec-ch-ua:
      "Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"
      10. sec-ch-ua-mobile:
      ?1
      11. sec-ch-ua-platform:
      "Android"
      12. Sec-Fetch-Dest:
      empty
      13. Sec-Fetch-Mode:
      cors
      14. Sec-Fetch-Site:
      same-origin
      15. User-Agent:
      Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N)
      AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Mobile
      Safari/537.36
      16. x-grafana-org-id:
      1
      3. Query String Parametersview sourceview decoded
      1. name:
      localhost



Here is a successful screenshot of a PI Web API request:
[image: image.png]

Thanks,
Alkarim

**Comment by coderReview** [comment]
For the postman are you using Basic Auth or no authentication at all? Also, the nessage format is all wrong here in the Github issue. Can you reply in the browser instead of using email?

**Comment by AlkarimSamji** [comment]
Sorry, here are the images from dev tools and postman attached through the web page now. They are attached.

![chrome-devtools](https://user-images.githubusercontent.com/15164452/133871367-ef12b1be-aa60-41ed-961d-c27210454dcf.png)

![postman](https://user-images.githubusercontent.com/15164452/133871379-63e326bd-de65-4d08-8230-1ad2c619db15.png)

**Comment by coderReview** [comment]
Can you set your CorsOrigins to "*"?

**Comment by AlkarimSamji** [comment]
Hello - I tried this but it did not help resolve the issue. I am still getting a bad gateway error.

**Comment by coderReview** [comment]
Are you running in docker? Can you disable windows firewall?

**Comment by coderReview** [comment]
I have never seen such issues. It seems a problem with your setup. I just don't know what

**Comment by AlkarimSamji** [comment]
No, not running on docker and no firewall installed. PI is on the same machine as AF, Web API, and Grafana.

**Comment by coderReview** [comment]
Can't reproduce. Please try this #62
