### ISSUE TITLE
Update datasource on Grafana website

### ISSUE THREAD

**Issue by EEParker** [GridProtectionAlliance/osisoftpi-grafana#5]
The package at https://grafana.com/plugins/gridprotectionalliance-osisoftpi-datasource/installation needs to be updated to the latest code.

**Comment by ritchiecarroll** [comment]
The PR for this update has been merged - as soon as they refresh their web site against the plug-in updates it should be available.

Thanks!
Ritchie

**Comment by EEParker** [comment]
Great! It looks like it updated. I wasn't sure about the update procedure.
