### ISSUE TITLE
TimeShift

### ISSUE THREAD

**Issue by AndreasFridh** [GridProtectionAlliance/osisoftpi-grafana#58]
Add time shift to query.

**Comment by AndreasFridh** [comment]
I understand that this feature is made on the Query options and will be used on all queries on that panel.

I do not know how and if Grafana could handle different times series in the same panel. 

I think we could drop this for now.

**Comment by Budilnik** [comment]
I also need this function. My production indicator ends at 07:00 of the current day, but this is the result for yesterday. Please reopen this issue.
