### ISSUE TITLE
Tag description from piwebapi

### ISSUE THREAD

**Issue by casperth** [GridProtectionAlliance/osisoftpi-grafana#60]
Hello,

Is there any way to retrieve the tag description and use it in a graph?

Greetings,
Casper

**Comment by bujos** [comment]
Any update for this question/ features ideas? thanks

**Comment by coderReview** [comment]
Can you provide more details on the request?

**Comment by bujos** [comment]
Is it possible to get the description value of a Pi Tag ?

**Comment by coderReview** [comment]
But where do you want to use that?

**Comment by bujos** [comment]
Maybe in tooltip when you search for a tag, like PiVision, or concat with tag name, and the description dissapear when you select the tag.

**Comment by coderReview** [comment]
Fixed in #107
