### ISSUE TITLE
Alpha numeric string values not displaying in Grafana

### ISSUE THREAD

**Issue by KRod-dmda** [GridProtectionAlliance/osisoftpi-grafana#64]
Updated dashboard from 7.0.5 to 8.3.6. OSISoft attribute strings results are being captured by query editor but not displaying on Grafana panels. Any idea how to resolve this issue?

![QueryEditor](https://user-images.githubusercontent.com/85301534/154551937-b1bc49e8-1b7f-49c8-8bf9-c6f3f831b715.JPG)

**Comment by coderReview** [comment]
Have you configured the table column to be interpreted as a String?

**Comment by KRod-dmda** [comment]
I have, but that does not resolve the issue. Any ideas on how to fix?
