### ISSUE TITLE
No manifest when manually installing Github OSI code

### ISSUE THREAD

**Issue by KRod-dmda** [GridProtectionAlliance/osisoftpi-grafana#65]
Whoops, I am really blowing up this thread 0.o. When downloading the GitHub file and restarting the Grafana service, the plugin is unsigned. I am unable to locate a manifest file,..any ideas on how to proceed?

![image](https://user-images.githubusercontent.com/85301534/154712210-f6dbead7-f231-4460-b8bf-a366cf087580.png)

My plugin directory
![image](https://user-images.githubusercontent.com/85301534/154712418-7c12f9e6-b465-49d0-90c7-ee2912b83c7d.png)

**Comment by coderReview** [comment]
See https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins

if you are using docker, you should environment variables.
