### ISSUE TITLE
Batch fetching of variables not workting.

### ISSUE THREAD

**Issue by AndreasFridh** [GridProtectionAlliance/osisoftpi-grafana#68]
I have tested this on my system now. 

Have not found any specific new problems yet, but annotation seems to be fetching the database at least now. Batch fetching of variable data in queries is still not correctly formatted and the API responds with error.

_Originally posted by @AndreasFridh in https://github.com/GridProtectionAlliance/osisoftpi-grafana/pull/62#issuecomment-1084495959_

Query inspector result:
```

{
  "request": {
    "url": "api/datasources/proxy/1/attributes?selectedFields=WebId;Name;Path&path=\\\\PI_AF\\AF Test\\I_is_element\\{Child_1,Child_2}|Attrib",
    "method": "GET",
    "hideFromInspector": false
  },
  "response": {
    "Errors": [
      "Not found: '\\\\PI_AF\\AF Test\\I_is_element\\{Child_1,Child_2}|Attrib'. Invalid object path format for '\\\\PI_AF\\AF Test\\I_is_element\\{Child_1,Child_2}|Attrib'.\r\nParameter name: path"
    ]
  }
}
```

**Comment by coderReview** [comment]
Can you provide the query used in the QueryEditor? thank you

**Comment by AndreasFridh** [comment]
I have a lot of elements with the same attributes in AF (template). And would like them to be shown in the same graph easily.

**Comment by AndreasFridh** [comment]
I am not selecting "All" I am selecting "Child_1" and "Child_2" out of 10 different elements in the AF structure.

**Comment by coderReview** [comment]
Using multiple option? Can you provide the variable definition?

**Comment by AndreasFridh** [comment]
![image](https://user-images.githubusercontent.com/46330513/161074194-7179564a-f38a-410a-8a5a-768ae904fcd3.png)

**Comment by coderReview** [comment]
So you are using the multi-value to select Child_1 and Child_2, right?

**Comment by coderReview** [comment]
Fixed in https://github.com/GridProtectionAlliance/osisoftpi-grafana/pull/62/commits/9a5caea9978d35698725b5e7b03e97e7bf1abf11
