### ISSUE TITLE
Edit mode clears previous queries 

### ISSUE THREAD

**Issue by ekimeel** [GridProtectionAlliance/osisoftpi-grafana#7]
Using Grafana 4.6.1 and OSI 1.0.1, switching to edit mode clears out the previous query.

**Comment by EEParker** [comment]
What browser version and operating system are you using? I am able to switch between edit and selection mode without issues. 

One possible scenario I can think of is if the element does not exist, when switching back to select mode it could the nodes in the hierarchy that cannot be found.

**Comment by coderReview** [comment]
@ritchiecarroll @EEParker I think latest version (tag v1.1.0) this is fixed. Can you check?

**Comment by coderReview** [comment]
Fixed by v2.0.0-beta - https://github.com/GridProtectionAlliance/osisoftpi-grafana/tree/v2.0.0-beta
