### ISSUE TITLE
Grafana plugin unavailable errror with Osi-pi plugin

### ISSUE THREAD

**Issue by mayur00077** [GridProtectionAlliance/osisoftpi-grafana#70]
I am getting an error while creating the alerts.
The Data Source I am using is  OSIsoft-PI-Monitoring.
The details are as per the snapshot.
![gr2](https://user-images.githubusercontent.com/104985920/166915551-e7d1c511-26db-429f-a077-5ca364879cab.PNG)
I am receiving the data from the plug-in but when I try to configure the alerts on that it is showing the error.

**Comment by coderReview** [comment]
@mayur00077 what version are you using? version 1.0 is no longer supported.

Also, v2.0.0-beta doesn't support alert yet.

**Comment by mayur00077** [comment]
I am currently using 1.1.1.

**Comment by coderReview** [comment]
Please use version 2.0.0.

Version 1.x is no longer supported.

Em qui., 5 de mai. de 2022 às 12:43, mayur00077 ***@***.***>
escreveu:

**Comment by coderReview** [comment]
But alerts is not yet part of the plugin.
Thanks

Em qui., 5 de mai. de 2022 às 12:57, Paulo Vitor Magacho da Silva <
***@***.***> escreveu:

**Comment by coderReview** [comment]
At the moment we don’t have support for alerts.

Em qui., 5 de mai. de 2022 às 13:08, mayur00077 ***@***.***>
escreveu:

**Comment by ericseanmoore** [comment]
So there is no current solution? Is there an ETA on support for alerts?

**Comment by coderReview** [comment]
There is no ETA for that

**Comment by clackner-gpa** [comment]
I will close this issue as this is not a feature currently supported or planned to be supported.
