### ISSUE TITLE
Query only uses the default AF Server and AF Database

### ISSUE THREAD

**Issue by Coding-Mike** [GridProtectionAlliance/osisoftpi-grafana#73]
Hello,

I updated to version 2.0.0 and I encountered an issue with the query editor. When you have a default AF Server and AF Database set in the DataSource settings than you can't choose a different AF Server or AF Database when you want to create a new query.

The query only allows the selection of the defined AF Database and AF Server from DataSource settings.

If you don't set default AF Server and AF Database you can freely query for any AF Server or Database.

The problem here is, that if you want to use Annotations you need to set a default AF Server in order to use them. The best approach here would be to allow the selection of AF Server in the annotation query control.

Kind regards
Michael

**Comment by coderReview** [comment]
@clackner-gpa @ritchiecarroll can you help what is the best option here? Thank you.

**Comment by clackner-gpa** [comment]
@Coding-Mike  I'm not quite sure I fully understand the issue. If you need annotations from a second PI instance you should be able to add a second datasource. There is no restriction on how many datasources of the same type can exists. I would caution against not setting a default server and database in the first place.

**Comment by Coding-Mike** [comment]
@clackner-gpa On our side we have the situation, that we have many different PI server and AF server. 
This would lead to many data sources that makes it difficult to find the right settings. 
Also the amount of AF databases is high. Many users also need the usage of different PI server, AF server and AF databases to query their data. 
It would be easier if you can create one datasource for PI and the users can choose their PI server, AF server and AF database for all query types.

With this approach you can have one datasource for each kind of data - one for PI, one for postgres ...

I hope this helps to understand the issue.

Kind regards
Michael

**Comment by coderReview** [comment]
@Coding-Mike I think you can set the PI server and AF server and leave the AF database empty. This would be a similar situation as a MySQL database that the user can select the tables. Different database means different datasource entry.
I will check if I can add AF database selection to annotation.

**Comment by coderReview** [comment]
@Coding-Mike can you check v3.0.0. If all is ok, I will close this issue

**Comment by coderReview** [comment]
This has been fixed. Version 4.0.0 will also fix annotations.
