### ISSUE TITLE
Digital States not working

### ISSUE THREAD

**Issue by Coding-Mike** [GridProtectionAlliance/osisoftpi-grafana#75]
Hello all,

I currently face an issue with digital states in the current version.
When I reference a digital state tag in the query and set the toggle digital state to true then the value is not shown as text but when I set digital state to off then I see the actual int value of the digital state.

What is causing this issue?

Kind regards
Michael

**Comment by Coding-Mike** [comment]
Since upload of the images doesn't work here as explaination:

In the first state with digital state on and set to table View in the query inspector you see [object Object] instead of the name. 

In the other situation you see the actual int value.

Kind regards
Michael

**Comment by coderReview** [comment]
Can you provide a screenshot of the tag configuration? You can use something like https://pasteboard.co/

**Comment by Coding-Mike** [comment]
Here are the pictures:
DigitalState: https://pasteboard.co/doEnD7EkSCor.png
Show as Value: https://pasteboard.co/ebKOId9vFUY1.png

Kind regards
Michael

**Comment by coderReview** [comment]
What is the expected result for Digital State? On/Off?

**Comment by Coding-Mike** [comment]
The expected values would be "AUF" and "ZU"

Query Inspector:
https://pasteboard.co/TEKOnQSMDJba.png

**Comment by coderReview** [comment]
Ok.

**Comment by Coding-Mike** [comment]
I checked the code and I think the missing part is, that in the QueryEditor.ts file the DigitalStates variable is not added to the State Interface and so I think it is always evaluated to false when data is loaded.

Kind regards
Michael

**Comment by coderReview** [comment]
Fixed in version 2.1.1
