### ISSUE TITLE
Variable in tag name not working

### ISSUE THREAD

**Issue by JohnBolander** [GridProtectionAlliance/osisoftpi-grafana#77]
I'm on version 2.0.0 of the grafana pi web api plug in. It appears that grafana variables aren't working in the tag name. I can manually type out the tag name with the variable, and it seems that the grafana is properly interpreting the variable, but that there is an extra space in the tag name that I can't get rid of. Is there a way to make this work? 

![image](https://user-images.githubusercontent.com/4633707/168863729-1c499d05-a25a-4541-ae4a-92e8024575c6.png)

**Comment by coderReview** [comment]
Will be fixed in version 2.1.0.

**Comment by coderReview** [comment]
Fixed in version 2.1.1
