### ISSUE TITLE
Grafana Upgrade - OSIsoft Plugin issue once again

### ISSUE THREAD

**Issue by KRod-dmda** [GridProtectionAlliance/osisoftpi-grafana#80]
Hello,

I decided to upgrade our dashboard from version 8.3.6 to 9 and now receiving the following error. Has anyone experienced this before or have any idea how to resolve?

![image](https://user-images.githubusercontent.com/85301534/171294870-6283fe0f-e99f-48a8-8e20-9df0c175733c.png)

Any advice is greatly appreciated. TIA

**Comment by coderReview** [comment]
Hello. We haven't tried version 9.0 yet. Also, I think latest stable version is v8.5.4 https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-5-4/

Can you revert to this version?

**Comment by KRod-dmda** [comment]
I have reverted to version 8.5.4, and the plugin is working again. Thank you!
