### ISSUE TITLE
Problems creating new data source - Bad Gateway

### ISSUE THREAD

**Issue by gschwepp** [GridProtectionAlliance/osisoftpi-grafana#81]
Hello, 

I have currently the problem that I cannot add an OSIsoft-PI data source to Grafana. 

## My Dev Environment:
Grafana and the piwebapi are running on the same computer. For this test I configured the piwebapi to also allow anonymous login. PI-AF, PI-DA and webapi are working properly, as I can query the information with my webbrowser. 

## The problem: 
When I add my webapi URL to the accodring field and hit "Save & Test" I get the notification *Bad Gateway*.
None of the settings seem to solve this problem. 

## Antoher Problem: 
As soon as I remove `/piwebapi`  from the URL the notifcation changes to *Data source is working*. But it is not. The notification stays the same regardless what I change. Even if I add `/piwebapi` again back to the URL. 

Both behaviours seem wrong to me. Do you require more information from me to resolve this issue? 

Thanks a lot.

**Comment by coderReview** [comment]
@gschwepp I don't think we ever tried anonymous login. Can you try with Basic authentication and see if that works.

**Comment by gschwepp** [comment]
Ok, Interesting. Section *Another Problem* does not occur if I try it without Anonymous login. 

However, *the Problem* still occurs. I configured the source as following:

![grafik](https://user-images.githubusercontent.com/6408236/173430360-363f8e64-45b0-4315-a6ca-237acdb999d6.png)

The provided server and the login credentials are correct. After a quick google search, this seems to be a common problem, but I did not find a definite answer to this issue. Any suggestion where to look? Both logs, granfana and piwebapi are not very informative.

**Comment by gschwepp** [comment]
Hi thank you for you quick response, 

this is interesting the *another problem* does not occur anymore. Anyhow the first problem still happens as described. I configured the datasource as following: 

![grafik](https://user-images.githubusercontent.com/6408236/173430795-0a6fe56e-fae1-4ae9-bc36-de345cc56558.png)

The credentials and the url for the webapi are correct. Any suggestions where to look? After a quick google search this seems to be a known issue, however I didn't find a definite answer to this. Do you have any suggestions where to look? Both, the grafana and the piwebapi logs are not too informative at this point. 

Thanks.

**Comment by coderReview** [comment]
You can enable debug in the grafana.ini file

**Comment by coderReview** [comment]
Also, please define the PI Server, PI AF server and PI Default Database

**Comment by coderReview** [comment]
I will close this. No more activity.
