### ISSUE TITLE
Disabling PI point search

### ISSUE THREAD

**Issue by janabala5** [GridProtectionAlliance/osisoftpi-grafana#82]
How to disable the PI point search?

I tried removing the PI server name from the admin page, but still PI server shows.

**Comment by coderReview** [comment]
what do you mean by disable PI point search? 

There is this option:

![image](https://user-images.githubusercontent.com/5925442/175127120-510c68da-42da-408a-a9f6-b538c3d021ba.png)

**Comment by coderReview** [comment]
Do you mean you want to disable  PI search altogether?

**Comment by janabala5** [comment]
Disable on Data source page.

so we could get one DS with pi point search and one without.

**Comment by TheFern2** [comment]
@coderReview I have completed this feature, we're just trying to figure out how to setup our internal enterprise repo to submit the PR. Should be able to submit PR soon.

**Comment by janabala5** [comment]
where can i download the latest code to test?

**Comment by coderReview** [comment]
Closed using #103
