### ISSUE TITLE
Feature request: Query and return elements based on attribute values

### ISSUE THREAD

**Issue by SC-66** [GridProtectionAlliance/osisoftpi-grafana#86]
It should be possible to query an AF structure with an attribute condition and only return the elements fulfilling the condition.
For example: If I have an variable called Machines with a list of element names and an attribute named MachineStatus, then raw query today looks like this:
PISERVER\DATABASE\AAA\BBB\CCC\\${Machines};MachineStatus
That query returns all elements of the variable list Machines and if I use Repeat by variable then the panel will be repeated for each item in the Machine list.

I want to be able to use the same variable list in the query but also include an attribute condition, something like this in raw format:
PISERVER\DATABASE\AAA\BBB\CCC\\${Machines};MachineStatus=3
That would then return all elements part of the Machines variable AND fulfilling the condition of having the attribute MachineStatus equal to 3.

**Comment by coderReview** [comment]
Is this possible using PI Web API?

You can do this using transformation.

**Comment by SC-66** [comment]
Hello!
I have not seen how it is possible using transformation? If I do it by
filter out values, the panel itself will still remain on the dashboard
"empty". I want the panel not to show at all if the element does not
fulfill the criterina.
BR,
/Stefan

Den lör 3 sep. 2022 kl 00:02 skrev Paulo Vitor Magacho <
***@***.***>:

**Comment by coderReview** [comment]
https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/transform-data/#filter-data-by-values
