### ISSUE TITLE
Time range includes last previous value even if outside time range

### ISSUE THREAD

**Issue by SC-66** [GridProtectionAlliance/osisoftpi-grafana#89]
I select time range "Today" in the dashboard, then the time range value is e.g. "2022-09-21 00:00:00 to 2022-09-21 23:59:59" which is as expected. 
Then if I have selected Calulation "Last *" the the query returns the last value for an attribute even of it is before the selected time range. The attribute has the latest recorded timestamp in OsiSoft PI previous  to the selected time range in the dashboard.

If I select Table view I can see that the attribute now is included in the query with time stamp "2022-09-21 00:00:00" and hence is shown in the panel even it is collected before time range.
Using "Last" as calculation don't help me since then the last value is not shown in the Stat panel as a number, only as a graph.

So how can I get the panel to only display the last value of an attribute that actually is recorded in PI within the selected time range?
(and excluding the last value previous to the time range)

**Comment by coderReview** [comment]
If you want this feature, just turn on the recorded flag. This will use the Record controller instead of the Plot controller.

**Comment by coderReview** [comment]
I will close this for now.
