### ISSUE TITLE
Feature request - Additional query options

### ISSUE THREAD

**Issue by alexl04** [GridProtectionAlliance/osisoftpi-grafana#96]
The following additional query options would be very welcome:

1. Query only the latest available data point of some measure
2. Grafana Alerting with OSI-Soft PI data sources
3. Grafana Dashboard Variables > type query > OSI-Soft PI datasource > query data and use for example the latest available data point as a dashboard variable. For example, query the latest latitude/longitude from some GPS device and use the coordinates in another query as a variable in an embedded Windy text panel for a weather forecast at the latest received position.

**Comment by coderReview** [comment]
1. Done in v3.1.0
2. Won't be fixed. Must use backend plugin with Go
3. To be done. At the moment this can be done with AF attribute value.

**Comment by alexl04** [comment]
> * Done in v3.1.0
> * Won't be fixed. Must use backend plugin with Go
> * At the moment this can be done with AF attribute value.

Thanks coderReview 🙏
